{
 "title": "Service Span Dashboard",
 "description": "Service Level Dashboard",
 "tags": [
  "apm-v3",
  "service",
  "tempo-mg",
  "operation"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{source=\"tempo\"},k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{source=\"tempo\", k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{source=\"tempo\", k8s_cluster_name=\"$cluster\", k8s_namespace_name=\"$namespace\", span_kind!=\"SPAN_KIND_CLIENT\"},service)"
    }
   },
   {
    "name": "span",
    "label": "Operation",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{source=\"tempo\", k8s_cluster_name=\"$cluster\", k8s_namespace_name=\"$namespace\", service=\"$service\"},span_name)"
    }
   },
   {
    "name": "rate_interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 🚨 Investigate RED Metrics\n\nPlease drill down to a 3-hour time window.\nThen, open the 🔗 Rate, Errors & Duration metrics panel links to investigate further."
   }
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "appo11y:request:rate5m{k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", span_name=~\"$span\"}",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "appo11y:error:ratio{k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", span_name=~\"$span\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "appo11y:duration:p99{k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", span_name=~\"$span\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "appo11y:duration:p95{k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", span_name=~\"$span\"}",
     "legendFormat": "P95"
    },
    {
     "expr": "appo11y:duration:avg{k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", span_name=~\"$span\"}",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Duration distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "appo11y:duration:distribution{k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", span_name=~\"$span\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}