{
 "title": "AWS-S3 (Cross-Account)",
 "description": "Visualize AWS S3 metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {}
   },
   {
    "name": "filterid",
    "label": "FilterId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "BucketSizeBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "StorageType": "StandardStorage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NumberOfObjects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "StorageType": "AllStorageTypes" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Filtered Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.BucketName')}",
     "metricName": "AllRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.BucketName')}",
     "metricName": "GetRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.BucketName')}",
     "metricName": "PutRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.BucketName')}",
     "metricName": "DeleteRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.BucketName')}",
     "metricName": "HeadRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.BucketName')}",
     "metricName": "PostRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.BucketName')}",
     "metricName": "ListRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Filtered Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FirstByteLatency",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Filtered Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Filtered Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4xxErrors",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "label": "${PROP('Dim.BucketName')}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "5xxErrors",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}