{
 "title": "AWS EFS (Cross-Account)",
 "description": "Visualize AWS EFS metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "filesystemid",
    "label": "FileSystemId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes/ClientConnections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.FileSystemId')}",
     "metricName": "DataReadIOBytes",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.FileSystemId')}",
     "metricName": "DataWriteIOBytes",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.FileSystemId')}",
     "metricName": "MetadataIOBytes",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.FileSystemId')}",
     "metricName": "ClientConnections",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "BurstCreditBalance/PermittedThroughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.FileSystemId')}",
     "metricName": "BurstCreditBalance",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.FileSystemId')}",
     "metricName": "PermittedThroughput",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PercentIOLimit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.FileSystemId')}",
     "metricName": "PercentIOLimit",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}