{
 "title": "AWS SQS (Cross-Account)",
 "description": "Visualize AWS SQS metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "queue",
    "label": "QueueName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ApproximateAgeOfOldestMessage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ApproximateNumberOfMessages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "ApproximateNumberOfMessagesDelayed",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NumberOfEmptyReceives",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "NumberOfEmptyReceives",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SentMessageSize",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "accountId": "$account",
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.QueueName')}",
     "metricName": "SentMessageSize",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}