{
 "title": "AWS DocumentDB (Cross-Account)",
 "description": "AWS documentDB dashboard from cloudwatch exporter",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "Identifier",
    "label": "Identifier",
    "query": {}
   },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "Database Connection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBInstanceIdentifier')}",
     "metricName": "DatabaseConnectionsMax",
     "namespace": "AWS/DocDB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database cursors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DatabaseCursorsMax",
     "namespace": "AWS/DocDB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "FreeLocalStorage",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "FreeableMemory",
     "namespace": "AWS/DocDB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "ReadLatency",
     "namespace": "AWS/DocDB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "WriteLatency",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Cluster Replica Lag Maximum",
   "type": "timeseries",
   "description": "The maximum amount of lag, in milliseconds, between the primary instance and each Amazon DocumentDB instance in the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DBClusterReplicaLagMaximum",
     "namespace": "AWS/DocDB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DatabaseConnectionsMax",
     "namespace": "AWS/DocDB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Cursors ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DatabaseCursors",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DatabaseCursorsMax",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cpu Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "FreeableMemory",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "BufferCacheHitRatio",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "WriteIOPS",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "ReadIOPS",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Volume IOPS rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "VolumeWriteIOPs",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "VolumeReadIOPs",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Volume Bytes Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "VolumeBytesUsed",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Local Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "FreeLocalStorage",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Throughtput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "ReadThroughput",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "WriteThroughput",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "NetworkThroughput",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "ReadLatency",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "WriteLatency",
     "namespace": "AWS/DocDB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Operations Documents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DocumentsDeleted",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DocumentsInserted",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DocumentsReturned",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "DocumentsUpdated",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Operation  Opcounters",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "OpcountersCommand",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "OpcountersDelete",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "OpcountersGetmore",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "OpcountersInsert",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "DBClusterIdentifier": "$Identifier" },
     "label": "${PROP('Dim.DBClusterIdentifier')}",
     "metricName": "OpcountersUpdate",
     "namespace": "AWS/DocDB",
     "period": "$period",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}