apiVersion: grizzly.grafana.com/v1alpha1
kind: DashboardFolder
metadata:
    name: integration-aws-cloudwatch-oam
spec:
    title: Integration-AWS-Cloudwatch-OAM
    uid: integration-aws-cloudwatch-oam
