apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: node-exporter-filesystem-alerts
    namespace: integration-linuxnode
spec:
    rules:
        - alerts: []
          annotations:
            description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.
            summary: Filesystem has less than 5% space left.
          duration: 1800
          labels:
            severity: warning
          name: NodeFilesystemAlmostOutOfSpace
          query: (node_filesystem_avail_bytes{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} / node_filesystem_size_bytes{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} * 100 < 5 and node_filesystem_readonly{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} == 0)
          type: alerting
        - alerts: []
          annotations:
            description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.
            summary: Filesystem has less than 3% space left.
          duration: 1800
          labels:
            severity: critical
          name: NodeFilesystemAlmostOutOfSpace
          query: (node_filesystem_avail_bytes{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} / node_filesystem_size_bytes{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} * 100 < 3 and node_filesystem_readonly{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} == 0)
          type: alerting
        - alerts: []
          annotations:
            description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up.
            summary: Filesystem is predicted to run out of inodes within the next 24 hours.
          duration: 3600
          labels:
            severity: warning
          name: NodeFilesystemFilesFillingUp
          query: (node_filesystem_files_free{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} / node_filesystem_files{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} * 100 < 40 and predict_linear(node_filesystem_files_free{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""}[6h], 24 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} == 0)
          type: alerting
        - alerts: []
          annotations:
            description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up fast.
            summary: Filesystem is predicted to run out of inodes within the next 4 hours.
          duration: 3600
          labels:
            severity: critical
          name: NodeFilesystemFilesFillingUp
          query: (node_filesystem_files_free{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} / node_filesystem_files{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} * 100 < 20 and predict_linear(node_filesystem_files_free{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""}[6h], 4 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} == 0)
          type: alerting
        - alerts: []
          annotations:
            description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.
            summary: Filesystem has less than 5% inodes left.
          duration: 3600
          labels:
            severity: warning
          name: NodeFilesystemAlmostOutOfFiles
          query: (node_filesystem_files_free{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} / node_filesystem_files{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} * 100 < 5 and node_filesystem_readonly{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} == 0)
          type: alerting
        - alerts: []
          annotations:
            description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.
            summary: Filesystem has less than 3% inodes left.
          duration: 3600
          labels:
            severity: critical
          name: NodeFilesystemAlmostOutOfFiles
          query: (node_filesystem_files_free{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} / node_filesystem_files{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} * 100 < 3 and node_filesystem_readonly{fstype!="",job=~"integrations/(node_exporter|unix)",mountpoint!=""} == 0)
          type: alerting
