{
 "title": "Linux node / fleet overview",
 "tags": [ "linuxnode-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\"}, job)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\"}, namespace)"
   },
   {
    "name": "allocationtags",
    "label": "Allocation Tags",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",namespace=~\"$namespace\"}, allocationtags)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"integrations/(node_exporter|unix)\"} == 1) > 0) and (absent(absent(node_uname_info{job=~\"integrations/(node_exporter|unix)\"})))) or vector(0) and on() ((count(up{job=~\"integrations/(node_exporter|unix)\"}) > 0) and (absent(node_uname_info{job=~\"integrations/(node_exporter|unix)\"})))\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"integrations/(node_exporter|unix)\"} == 1) > 0) and (absent(absent(node_uname_info{job=~\"integrations/(node_exporter|unix)\"})))) or vector(0) and on() ((count(up{job=~\"integrations/(node_exporter|unix)\"}) > 0) and (absent(node_uname_info{job=~\"integrations/(node_exporter|unix)\"})))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fleet overview",
   "type": "table",
   "description": "All nodes' perfomance at a glance.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"} \n* on (cluster,job,instance)\ngroup_left(pretty_name)\nnode_os_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}\n"
    },
    {
     "expr": "time() - node_boot_time_seconds{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}"
    },
    {
     "expr": "node_load1{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\", mode=\"idle\"})",
     "legendFormat": "Cores"
    },
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) by (cpu, instance))\n",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}",
     "legendFormat": "Memory total"
    },
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"})\n* 100\n)\n"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\", mountpoint=\"/\", fstype!=\"rootfs\"}"
    },
    {
     "expr": "100 - node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}*100"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\", alertstate=\"firing\", severity=\"critical\"}[1m])) * group by (instance) (node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"})"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\", alertstate=\"firing\", severity=\"warning\"}[1m])) * group by (instance) (node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,(((count by (instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) by (cpu, instance))\n)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg((((count by (instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) by (cpu, instance))\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"})\n* 100\n)\n)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"})\n* 100\n)\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,irate(node_disk_io_time_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\", device!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{volume}}"
    },
    {
     "expr": "avg(irate(node_disk_io_time_seconds_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\", device!=\"\"}[$__rate_interval]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,100 - node_filesystem_avail_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}/node_filesystem_size_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}*100)",
     "legendFormat": "{{instance}}: {{volume}}"
    },
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}/node_filesystem_size_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}*100)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Network errors and dropped packets",
   "type": "timeseries",
   "description": "Top 25.\n\n**Network errors**:\n\nNetwork errors refer to issues that occur during the transmission of data across a network. \n\nThese errors can result from various factors, including physical issues, jitter, collisions, noise and interference.\n\nMonitoring network errors is essential for diagnosing and resolving issues, as they can indicate problems with network hardware or environmental factors affecting network quality.\n\n**Dropped packets**:\n\nDropped packets occur when data packets traveling through a network are intentionally discarded or lost due to congestion, resource limitations, or network configuration issues. \n\nCommon causes include network congestion, buffer overflows, QoS settings, and network errors, as corrupted or incomplete packets may be discarded by receiving devices.\n\nDropped packets can impact network performance and lead to issues such as degraded voice or video quality in real-time applications.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25, irate(node_network_transmit_errs_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}[$__rate_interval]))>0",
     "legendFormat": "{{instance}}: {{ device }} errors transmitted"
    },
    {
     "expr": "topk(25, irate(node_network_receive_errs_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}[$__rate_interval]))>0",
     "legendFormat": "{{instance}}: {{ device }} errors received"
    },
    {
     "expr": "topk(25, irate(node_network_transmit_drop_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}[$__rate_interval]))>0",
     "legendFormat": "{{instance}}: {{ device }} transmitted dropped"
    },
    {
     "expr": "topk(25, irate(node_network_receive_drop_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",allocationtags=~\"$allocationtags\",namespace=~\"$namespace\"}[$__rate_interval]))>0",
     "legendFormat": "{{instance}}: {{ device }} received dropped"
    }
   ]
  }
 ]
}