apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_compactor_alerts
    namespace: integration-mimir
spec:
    rules:
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has not successfully cleaned up blocks in the last 6 hours.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasnotsuccessfullycleanedupblocks
          duration: 3600
          labels:
            severity: critical
          name: MimirCompactorHasNotSuccessfullyCleanedUpBlocks
          query: (time() - cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds > 60 * 60 * 6)
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has not run compaction in the last 24 hours.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasnotsuccessfullyruncompaction
          duration: 3600
          labels:
            reason: in-last-24h
            severity: critical
          name: MimirCompactorHasNotSuccessfullyRunCompaction
          query: (time() - cortex_compactor_last_successful_run_timestamp_seconds > 60 * 60 * 24) and (cortex_compactor_last_successful_run_timestamp_seconds > 0)
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has not run compaction in the last 24 hours.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasnotsuccessfullyruncompaction
          duration: 86400
          labels:
            reason: since-startup
            severity: critical
          name: MimirCompactorHasNotSuccessfullyRunCompaction
          query: cortex_compactor_last_successful_run_timestamp_seconds == 0
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} failed to run 2 consecutive compactions.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasnotsuccessfullyruncompaction
          duration: 0
          labels:
            reason: consecutive-failures
            severity: critical
          name: MimirCompactorHasNotSuccessfullyRunCompaction
          query: increase(cortex_compactor_runs_failed_total{reason!="shutdown"}[2h]) >= 2
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has run out of disk space.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasrunoutofdiskspace
          duration: 0
          labels:
            reason: non-transient
            severity: critical
          name: MimirCompactorHasRunOutOfDiskSpace
          query: increase(cortex_compactor_disk_out_of_space_errors_total[1d]) >= 1
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has not uploaded any block in the last 24 hours.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasnotuploadedblocks
          duration: 900
          labels:
            severity: critical
            time_period: 24h
          name: MimirCompactorHasNotUploadedBlocks
          query: (time() - (max by (cluster, namespace, pod) (thanos_objstore_bucket_last_successful_upload_time{component="compactor"})) > 60 * 60 * 24) and (max by (cluster, namespace, pod) (thanos_objstore_bucket_last_successful_upload_time{component="compactor"}) > 0) and (sum by (cluster, namespace, pod) (rate(cortex_compactor_group_compaction_runs_started_total[1d])) > 0)
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has not uploaded any block since its start.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasnotuploadedblocks
          duration: 86400
          labels:
            severity: critical
            time_period: since-start
          name: MimirCompactorHasNotUploadedBlocks
          query: (max by (cluster, namespace, pod) (thanos_objstore_bucket_last_successful_upload_time{component="compactor"}) == 0) and (sum by (cluster, namespace, pod) (rate(cortex_compactor_group_compaction_runs_started_total[1d])) > 0)
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has found and ignored unhealthy blocks.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorskippedunhealthyblocks
          duration: 60
          labels:
            severity: warning
          name: MimirCompactorSkippedUnhealthyBlocks
          query: increase(cortex_compactor_blocks_marked_for_no_compaction_total[5m]) > 0
          type: alerting
        - alerts: []
          annotations:
            message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace }} has found and ignored unhealthy blocks.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorskippedunhealthyblocks
          duration: 1800
          labels:
            severity: critical
          name: MimirCompactorSkippedUnhealthyBlocks
          query: increase(cortex_compactor_blocks_marked_for_no_compaction_total[5m]) > 1
          type: alerting
