apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_exemplars_ingested
    namespace: integration-mimir
spec:
    rules:
        - evaluationTime: 0.001930549
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:01.127465949Z"
          name: cluster_namespace_job:cortex_ingester_ingested_exemplars:rate5m
          query: sum by (cluster, namespace, job) (rate(cortex_ingester_ingested_exemplars_total[5m]))
          type: recording
