apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: etcd_alerts
    namespace: integration-mimir
spec:
    rules:
        - alerts: []
          annotations:
            message: |
                Too much memory being used by {{ $labels.namespace }}/{{ $labels.pod }} - bump memory limit.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#etcdallocatingtoomuchmemory
          duration: 900
          labels:
            severity: warning
          name: EtcdAllocatingTooMuchMemory
          query: (container_memory_working_set_bytes{container="etcd"} / (container_spec_memory_limit_bytes{container="etcd"} > 0)) > 0.65
          type: alerting
        - alerts: []
          annotations:
            message: |
                Too much memory being used by {{ $labels.namespace }}/{{ $labels.pod }} - bump memory limit.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#etcdallocatingtoomuchmemory
          duration: 900
          labels:
            severity: critical
          name: EtcdAllocatingTooMuchMemory
          query: (container_memory_working_set_bytes{container="etcd"} / (container_spec_memory_limit_bytes{container="etcd"} > 0)) > 0.8
          type: alerting
