apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_autoscaling
    namespace: integration-mimir
spec:
    rules:
        - alerts: []
          annotations:
            message: The Horizontal Pod Autoscaler (HPA) {{ $labels.horizontalpodautoscaler }} in {{ $labels.namespace }} is not active.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimirautoscalernotactive
          duration: 3600
          evaluationTime: 0.002505562
          health: ok
          keepFiringFor: 0
          labels:
            severity: critical
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:29.207713794Z"
          name: MimirAutoscalerNotActive
          query: (label_replace((kube_horizontalpodautoscaler_status_condition{condition="ScalingActive",status="false"} * on (cluster, namespace) group_left () max by (cluster, namespace) (cortex_build_info) + on (cluster, namespace, horizontalpodautoscaler) group_right () max by (cluster, namespace, horizontalpodautoscaler) (label_replace(kube_horizontalpodautoscaler_spec_target_metric * 0, "metric", "$1", "metric_name", "(.+)")) > 0), "scaledObject", "$1", "horizontalpodautoscaler", "keda-hpa-(.*)")) and on (cluster, namespace, metric, scaledObject) (max by (cluster, namespace, metric, scaledObject) (label_replace(keda_scaler_metrics_value, "namespace", "$0", "exported_namespace", ".+") > 0))
          state: inactive
          type: alerting
        - alerts: []
          annotations:
            message: The Keda ScaledObject {{ $labels.scaledObject }} in {{ $labels.namespace }} is experiencing errors.
            runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimirautoscalerkedafailing
          duration: 3600
          evaluationTime: 0.001519693
          health: ok
          keepFiringFor: 0
          labels:
            severity: critical
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:29.210226379Z"
          name: MimirAutoscalerKedaFailing
          query: (label_replace(rate(keda_scaler_errors[5m]), "namespace", "$1", "exported_namespace", "(.*)") * on (cluster, namespace) group_left () max by (cluster, namespace) (cortex_build_info)) > 0
          state: inactive
          type: alerting
