apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_api_3
    namespace: integration-mimir
spec:
    rules:
        - evaluationTime: 0.014775807
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:03.047827605Z"
          name: cluster_namespace_job_route:cortex_request_duration_seconds:99quantile
          query: histogram_quantile(0.99, sum by (le, cluster, namespace, job, route) (rate(cortex_request_duration_seconds_bucket[1m])))
          type: recording
        - evaluationTime: 0.015879261
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:03.062618731Z"
          name: cluster_namespace_job_route:cortex_request_duration_seconds:50quantile
          query: histogram_quantile(0.5, sum by (le, cluster, namespace, job, route) (rate(cortex_request_duration_seconds_bucket[1m])))
          type: recording
        - evaluationTime: 0.003759708
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:03.078516018Z"
          name: cluster_namespace_job_route:cortex_request_duration_seconds:avg
          query: sum by (cluster, namespace, job, route) (rate(cortex_request_duration_seconds_sum[1m])) / sum by (cluster, namespace, job, route) (rate(cortex_request_duration_seconds_count[1m]))
          type: recording
        - evaluationTime: 0.028244561
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:03.082284621Z"
          name: cluster_namespace_job_route:cortex_request_duration_seconds_bucket:sum_rate
          query: sum by (le, cluster, namespace, job, route) (rate(cortex_request_duration_seconds_bucket[1m]))
          type: recording
        - evaluationTime: 0.003949227
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:03.110552533Z"
          name: cluster_namespace_job_route:cortex_request_duration_seconds_sum:sum_rate
          query: sum by (cluster, namespace, job, route) (rate(cortex_request_duration_seconds_sum[1m]))
          type: recording
        - evaluationTime: 0.002200033
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:03.114513838Z"
          name: cluster_namespace_job_route:cortex_request_duration_seconds_count:sum_rate
          query: sum by (cluster, namespace, job, route) (rate(cortex_request_duration_seconds_count[1m]))
          type: recording
        - evaluationTime: 0.00100552
          health: ok
          labels: {}
          lastError: ""
          lastEvaluation: "2025-04-18T10:11:03.116724857Z"
          name: cluster_namespace_job_route:cortex_request_duration_seconds:sum_rate
          query: sum by (cluster, namespace, job, route) (rate(cortex_request_duration_seconds[1m]))
          type: recording
