apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_exemplars_ingested
    namespace: integration-mimir
spec:
    rules:
        - labels: {}
          name: cluster_namespace_job:cortex_ingester_ingested_exemplars:rate5m
          query: sum by (cluster, namespace, job) (rate(cortex_ingester_ingested_exemplars_total[5m]))
          type: recording
