apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_alertmanager_rules
    namespace: integration-mimir
spec:
    rules:
        - labels: {}
          name: cluster_job_pod:cortex_alertmanager_alerts:sum
          query: sum by (cluster, job, pod) (cortex_alertmanager_alerts)
          type: recording
        - labels: {}
          name: cluster_job_pod:cortex_alertmanager_silences:sum
          query: sum by (cluster, job, pod) (cortex_alertmanager_silences)
          type: recording
        - labels: {}
          name: cluster_job:cortex_alertmanager_alerts_received_total:rate5m
          query: sum by (cluster, job) (rate(cortex_alertmanager_alerts_received_total[5m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_alertmanager_alerts_invalid_total:rate5m
          query: sum by (cluster, job) (rate(cortex_alertmanager_alerts_invalid_total[5m]))
          type: recording
        - labels: {}
          name: cluster_job_integration:cortex_alertmanager_notifications_total:rate5m
          query: sum by (cluster, job, integration) (rate(cortex_alertmanager_notifications_total[5m]))
          type: recording
        - labels: {}
          name: cluster_job_integration:cortex_alertmanager_notifications_failed_total:rate5m
          query: sum by (cluster, job, integration) (rate(cortex_alertmanager_notifications_failed_total[5m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_alertmanager_state_replication_total:rate5m
          query: sum by (cluster, job) (rate(cortex_alertmanager_state_replication_total[5m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_alertmanager_state_replication_failed_total:rate5m
          query: sum by (cluster, job) (rate(cortex_alertmanager_state_replication_failed_total[5m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_alertmanager_partial_state_merges_total:rate5m
          query: sum by (cluster, job) (rate(cortex_alertmanager_partial_state_merges_total[5m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_alertmanager_partial_state_merges_failed_total:rate5m
          query: sum by (cluster, job) (rate(cortex_alertmanager_partial_state_merges_failed_total[5m]))
          type: recording
