apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_exemplars_in
    namespace: integration-mimir
spec:
    rules:
        - labels: {}
          name: cluster_namespace_job:cortex_distributor_exemplars_in:rate5m
          query: sum by (cluster, namespace, job) (rate(cortex_distributor_exemplars_in_total[5m]))
          type: recording
