apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_ingester_rules
    namespace: integration-mimir
spec:
    rules:
        - labels: {}
          name: cluster_namespace_pod:cortex_ingester_ingested_samples_total:rate1m
          query: sum by (cluster, namespace, pod) (rate(cortex_ingester_ingested_samples_total[1m]))
          type: recording
