apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: mimir_querier_api
    namespace: integration-mimir
spec:
    rules:
        - labels: {}
          name: cluster_job:cortex_querier_request_duration_seconds:99quantile
          query: histogram_quantile(0.99, sum by (le, cluster, job) (rate(cortex_querier_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_job:cortex_querier_request_duration_seconds:50quantile
          query: histogram_quantile(0.5, sum by (le, cluster, job) (rate(cortex_querier_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_job:cortex_querier_request_duration_seconds:avg
          query: sum by (cluster, job) (rate(cortex_querier_request_duration_seconds_sum[1m])) / sum by (cluster, job) (rate(cortex_querier_request_duration_seconds_count[1m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_querier_request_duration_seconds_bucket:sum_rate
          query: sum by (le, cluster, job) (rate(cortex_querier_request_duration_seconds_bucket[1m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_querier_request_duration_seconds_sum:sum_rate
          query: sum by (cluster, job) (rate(cortex_querier_request_duration_seconds_sum[1m]))
          type: recording
        - labels: {}
          name: cluster_job:cortex_querier_request_duration_seconds_count:sum_rate
          query: sum by (cluster, job) (rate(cortex_querier_request_duration_seconds_count[1m]))
          type: recording
        - labels: {}
          name: cluster_job_route:cortex_querier_request_duration_seconds:99quantile
          query: histogram_quantile(0.99, sum by (le, cluster, job, route) (rate(cortex_querier_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_job_route:cortex_querier_request_duration_seconds:50quantile
          query: histogram_quantile(0.5, sum by (le, cluster, job, route) (rate(cortex_querier_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_job_route:cortex_querier_request_duration_seconds:avg
          query: sum by (cluster, job, route) (rate(cortex_querier_request_duration_seconds_sum[1m])) / sum by (cluster, job, route) (rate(cortex_querier_request_duration_seconds_count[1m]))
          type: recording
        - labels: {}
          name: cluster_job_route:cortex_querier_request_duration_seconds_bucket:sum_rate
          query: sum by (le, cluster, job, route) (rate(cortex_querier_request_duration_seconds_bucket[1m]))
          type: recording
        - labels: {}
          name: cluster_job_route:cortex_querier_request_duration_seconds_sum:sum_rate
          query: sum by (cluster, job, route) (rate(cortex_querier_request_duration_seconds_sum[1m]))
          type: recording
        - labels: {}
          name: cluster_job_route:cortex_querier_request_duration_seconds_count:sum_rate
          query: sum by (cluster, job, route) (rate(cortex_querier_request_duration_seconds_count[1m]))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:cortex_querier_request_duration_seconds:99quantile
          query: histogram_quantile(0.99, sum by (le, cluster, namespace, job, route) (rate(cortex_querier_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:cortex_querier_request_duration_seconds:50quantile
          query: histogram_quantile(0.5, sum by (le, cluster, namespace, job, route) (rate(cortex_querier_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:cortex_querier_request_duration_seconds:avg
          query: sum by (cluster, namespace, job, route) (rate(cortex_querier_request_duration_seconds_sum[1m])) / sum by (cluster, namespace, job, route) (rate(cortex_querier_request_duration_seconds_count[1m]))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:cortex_querier_request_duration_seconds_bucket:sum_rate
          query: sum by (le, cluster, namespace, job, route) (rate(cortex_querier_request_duration_seconds_bucket[1m]))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:cortex_querier_request_duration_seconds_sum:sum_rate
          query: sum by (cluster, namespace, job, route) (rate(cortex_querier_request_duration_seconds_sum[1m]))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:cortex_querier_request_duration_seconds_count:sum_rate
          query: sum by (cluster, namespace, job, route) (rate(cortex_querier_request_duration_seconds_count[1m]))
          type: recording
