{
 "title": "(Home) Kubernetes Integration",
 "tags": [
  "kubernetes-integration",
  "Start Here"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job!=\"\"}, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kubelet_runtime_operations_total{cluster=\"$cluster\", job!=\"\"}, instance)"
    }
   },
   { "name": "lokids", "label": "Events Data Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"padding: 10px;\">\n  <div style=\"margin-bottom: 30px;display: flex; flex-direction: row; align-items: center; margin-top: 10px;\">\n    <img style=\"height: 40px; width: 40px; margin-right: 10px;\" src=\"https://storage.googleapis.com/grafanalabs-integration-logos/kubernetes.svg\" />\n    <h2 style=\"margin-top: 5px;\">Welcome to DuploCloud for Kubernetes</h2>\n  </div>\n</div>"
   }
  },
  {
   "title": "Configuration status",
   "type": "stat",
   "description": "Configuration status.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster) (\n    count by (cluster, node) (kubelet_node_name{cluster=\"$cluster\"}) > 1 OR\n    topk(1, kubelet_node_name{cluster=\"$cluster\"}) OR\n    1-absent(kubelet_node_name{cluster=\"$cluster\"})\n)",
     "legendFormat": "Kubelet"
    },
    {
     "expr": "max by (cluster) (\n    count by (cluster, node) (kube_node_info{cluster=\"$cluster\"}) > 1 OR\n    topk(1, kube_node_info{cluster=\"$cluster\"}) OR\n    1-absent(kube_node_info{cluster=\"$cluster\"})\n)",
     "legendFormat": "Kube State Metrics"
    },
    {
     "expr": "max by (cluster) (\n    count by (cluster, instance) (machine_memory_bytes{cluster=\"$cluster\"} /\n        machine_memory_bytes{cluster=\"$cluster\"}) > 1 OR\n    topk(1, machine_memory_bytes{cluster=\"$cluster\"} /\n        machine_memory_bytes{cluster=\"$cluster\"}) OR\n    1-absent(machine_memory_bytes{cluster=\"$cluster\"})\n)",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "max by (cluster) (\n    count by (cluster, instance) (node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"} /\n        node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"}) > 1 OR\n    topk(1, node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"} /\n        node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"}) OR\n    1-absent(node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"})\n)",
     "legendFormat": "Node Exporter"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": {
    "content": "<h3>Resource consumption visibility</h3>\n<p>We provide 7 pre-built dashboards that give you visibility into resource consumption, with drilldowns by cluster, Namespace, Pod, Node and more.</p>"
   }
  },
  {
   "title": "Running pods",
   "type": "stat",
   "description": "Running pods.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"}) OR sum(kubelet_running_pod_count{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "description": "Running containers.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"}) OR sum(kubelet_running_container_count{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Resource consumption visibility",
   "type": "dashlist",
   "description": "Resource consumption visibility.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 }
  },
  {
   "title": "Cluster CPU usage (by Namespace)",
   "type": "timeseries",
   "description": "Cluster CPU usage (by Namespace).",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "options": {
    "content": "<h3>Cluster operations visibility</h3>\n<p>We provide 2 pre-built dashboards that give you visibility into the operations of your K8s clusters, including Kubelet metrics and Persistent Volumes.</p>\n<a href=\"https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/\" target=\"_blank\">Read more about Kubelet ></a>"
   }
  },
  {
   "title": "Events",
   "type": "logs",
   "description": "Events.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{job!=\"\", cluster=\"$cluster\"} | logfmt | line_format \"{{.kind}} {{.name}}: {{.msg}}\""
    }
   ]
  },
  { "title": "Cluster operations visibility", "type": "dashlist", "description": "Cluster operations visibility.", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 } }
 ]
}