apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: k8s.rules.container_memory_requests
    namespace: integrations-kubernetes-container
spec:
    rules:
        - name: cluster:namespace:pod_memory:active:kube_pod_container_resource_requests
          labels: {}
          query: kube_pod_container_resource_requests{job="integrations/kubernetes/kube-state-metrics",resource="memory"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~"Pending|Running"} == 1))
          type: recording
        - name: namespace_memory:kube_pod_container_resource_requests:sum
          labels: {}
          query: sum by (namespace, cluster) (sum by (namespace, pod, cluster) (max by (namespace, pod, container, cluster) (kube_pod_container_resource_requests{job="integrations/kubernetes/kube-state-metrics",resource="memory"}) * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~"Pending|Running"} == 1)))
          type: recording
