apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: k8s.rules.container_memory_swap
    namespace: integrations-kubernetes-container
spec:
    rules:
        - name: node_namespace_pod_container:container_memory_swap
          labels: {}
          query: container_memory_swap{image!="",job="integrations/kubernetes/cadvisor"} * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
          type: recording
