apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kubernetes-resources
    namespace: integrations-kubernetes
spec:
    rules:
        - alerts:
            - annotations:
                description: Cluster duploinfra-o11y has overcommitted CPU resource requests for Pods by 2.9830000000000005 CPU shares and cannot tolerate node failure.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit
                summary: Cluster has overcommitted CPU resource requests.
              labels:
                alertname: KubeCPUOvercommit
                cluster: duploinfra-o11y
                severity: warning
              value: "2.9830000000000005e+00"
          annotations:
            description: Cluster {{ $labels.cluster }} has overcommitted CPU resource requests for Pods by {{ $value }} CPU shares and cannot tolerate node failure.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit
            summary: Cluster has overcommitted CPU resource requests.
          duration: 600
          labels:
            severity: warning
          name: KubeCPUOvercommit
          query: sum by (cluster) (namespace_cpu:kube_pod_container_resource_requests:sum) - (sum by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="cpu"}) - max by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="cpu"})) > 0 and (sum by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="cpu"}) - max by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="cpu"})) > 0
          type: alerting
        - alerts:
            - annotations:
                description: Cluster duploinfra-o11y has overcommitted memory resource requests for Pods by 3.419G bytes and cannot tolerate node failure.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememoryovercommit
                summary: Cluster has overcommitted memory resource requests.
              labels:
                alertname: KubeMemoryOvercommit
                cluster: duploinfra-o11y
                severity: warning
              value: "3.418611712e+09"
          annotations:
            description: Cluster {{ $labels.cluster }} has overcommitted memory resource requests for Pods by {{ $value | humanize }} bytes and cannot tolerate node failure.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememoryovercommit
            summary: Cluster has overcommitted memory resource requests.
          duration: 600
          labels:
            severity: warning
          name: KubeMemoryOvercommit
          query: sum by (cluster) (namespace_memory:kube_pod_container_resource_requests:sum) - (sum by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="memory"}) - max by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="memory"})) > 0 and (sum by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="memory"}) - max by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="memory"})) > 0
          type: alerting
        - alerts: []
          annotations:
            description: Cluster {{ $labels.cluster }}  has overcommitted CPU resource requests for Namespaces.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuquotaovercommit
            summary: Cluster has overcommitted CPU resource requests.
          duration: 300
          labels:
            severity: warning
          name: KubeCPUQuotaOvercommit
          query: sum by (cluster) (min without (resource) (kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",resource=~"(cpu|requests.cpu)",type="hard"})) / sum by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="cpu"}) > 1.5
          type: alerting
        - alerts: []
          annotations:
            description: Cluster {{ $labels.cluster }}  has overcommitted memory resource requests for Namespaces.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememoryquotaovercommit
            summary: Cluster has overcommitted memory resource requests.
          duration: 300
          labels:
            severity: warning
          name: KubeMemoryQuotaOvercommit
          query: sum by (cluster) (min without (resource) (kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",resource=~"(memory|requests.memory)",type="hard"})) / sum by (cluster) (kube_node_status_allocatable{job="integrations/kubernetes/kube-state-metrics",resource="memory"}) > 1.5
          type: alerting
        - alerts: []
          annotations:
            description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaalmostfull
            summary: Namespace quota is going to be full.
          duration: 900
          labels:
            severity: info
          name: KubeQuotaAlmostFull
          query: kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",type="used"} / ignoring (instance, job, type) (kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",type="hard"} > 0) > 0.9 < 1
          type: alerting
        - alerts: []
          annotations:
            description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotafullyused
            summary: Namespace quota is fully used.
          duration: 900
          labels:
            severity: info
          name: KubeQuotaFullyUsed
          query: kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",type="used"} / ignoring (instance, job, type) (kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",type="hard"} > 0) == 1
          type: alerting
        - alerts: []
          annotations:
            description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaexceeded
            summary: Namespace quota has exceeded the limits.
          duration: 900
          labels:
            severity: warning
          name: KubeQuotaExceeded
          query: kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",type="used"} / ignoring (instance, job, type) (kube_resourcequota{job="integrations/kubernetes/kube-state-metrics",type="hard"} > 0) > 1
          type: alerting
        - alerts:
            - annotations:
                description: 82.47% throttling of CPU in namespace duploservices-otel-o11y for container node-exporter in pod duplo-monitoring-prometheus-node-exporter-pg6dk on cluster duploinfra-o11y.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh
                summary: Processes experience elevated CPU throttling.
              labels:
                alertname: CPUThrottlingHigh
                cluster: duploinfra-o11y
                container: node-exporter
                instance: ip-10-222-14-103.us-west-2.compute.internal
                namespace: duploservices-otel-o11y
                pod: duplo-monitoring-prometheus-node-exporter-pg6dk
                severity: info
              value: "8.247422680412371e-01"
            - annotations:
                description: 30.77% throttling of CPU in namespace duploservices-otel-o11y for container node-exporter in pod duplo-monitoring-prometheus-node-exporter-ww6kw on cluster duploinfra-o11y.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh
                summary: Processes experience elevated CPU throttling.
              labels:
                alertname: CPUThrottlingHigh
                cluster: duploinfra-o11y
                container: node-exporter
                instance: ip-10-222-12-139.us-west-2.compute.internal
                namespace: duploservices-otel-o11y
                pod: duplo-monitoring-prometheus-node-exporter-ww6kw
                severity: info
              value: "3.076923076923077e-01"
            - activeAt: "2025-02-06T11:14:17.78388913Z"
              annotations:
                description: 62.07% throttling of CPU in namespace duploservices-otel-o11y for container node-exporter in pod duplo-monitoring-prometheus-node-exporter-bzxw6 on cluster duploinfra-o11y.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh
                summary: Processes experience elevated CPU throttling.
              labels:
                alertname: CPUThrottlingHigh
                cluster: duploinfra-o11y
                container: node-exporter
                instance: ip-10-222-12-59.us-west-2.compute.internal
                namespace: duploservices-otel-o11y
                pod: duplo-monitoring-prometheus-node-exporter-bzxw6
                severity: info
              value: "6.206896551724138e-01"
          annotations:
            description: '{{ $value | humanizePercentage }} throttling of CPU in namespace {{ $labels.namespace }} for container {{ $labels.container }} in pod {{ $labels.pod }} on cluster {{ $labels.cluster }}.'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh
            summary: Processes experience elevated CPU throttling.
          duration: 900
          labels:
            severity: info
          name: CPUThrottlingHigh
          query: sum without (id, metrics_path, name, image, endpoint, job, node) (increase(container_cpu_cfs_throttled_periods_total{container!="",job="integrations/kubernetes/cadvisor"}[5m])) / sum without (id, metrics_path, name, image, endpoint, job, node) (increase(container_cpu_cfs_periods_total{job="integrations/kubernetes/cadvisor"}[5m])) > (25 / 100)
          type: alerting
