apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kubernetes-apps
    namespace: integrations-kubernetes
spec:
    rules:
        - alerts:
            - annotations:
                description: 'Pod duploservices-otel-o11y/duplo-monitoring-beyla-2vsk2 (beyla) is in waiting state (reason: "CrashLoopBackOff") on cluster duploinfra-o11y.'
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
                summary: Pod is crash looping.
              labels:
                alertname: KubePodCrashLooping
                cluster: duploinfra-o11y
                container: beyla
                instance: duplo-monitoring-kube-state-metrics.duploservices-otel-o11y.svc:8080
                job: integrations/kubernetes/kube-state-metrics
                namespace: duploservices-otel-o11y
                pod: duplo-monitoring-beyla-2vsk2
                reason: CrashLoopBackOff
                severity: warning
              value: "1e+00"
          annotations:
            description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is in waiting state (reason: "CrashLoopBackOff") on cluster {{ $labels.cluster }}.'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
            summary: Pod is crash looping.
          duration: 900
          labels:
            severity: warning
          name: KubePodCrashLooping
          query: max_over_time(kube_pod_container_status_waiting_reason{job="integrations/kubernetes/kube-state-metrics",reason="CrashLoopBackOff"}[5m]) >= 1
          type: alerting
        - alerts:
            - annotations:
                description: Pod kube-system/node-shell-d862377e-4924-40a5-aebe-da62ca8b17a0 has been in a non-ready state for longer than 15 minutes on cluster duploinfra-o11y.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
                summary: Pod has been in a non-ready state for more than 15 minutes.
              labels:
                alertname: KubePodNotReady
                cluster: duploinfra-o11y
                namespace: kube-system
                pod: node-shell-d862377e-4924-40a5-aebe-da62ca8b17a0
                severity: warning
              value: "1e+00"
          annotations:
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
            summary: Pod has been in a non-ready state for more than 15 minutes.
          duration: 900
          labels:
            severity: warning
          name: KubePodNotReady
          query: sum by (namespace, pod, cluster) (max by (namespace, pod, cluster) (kube_pod_status_phase{job="integrations/kubernetes/kube-state-metrics",phase=~"Pending|Unknown|Failed"}) * on (namespace, pod, cluster) group_left (owner_kind) topk by (namespace, pod, cluster) (1, max by (namespace, pod, owner_kind, cluster) (kube_pod_owner{owner_kind!="Job"}))) > 0
          type: alerting
        - alerts: []
          annotations:
            description: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match, this indicates that the Deployment has failed but has not been rolled back on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
            summary: Deployment generation mismatch due to possible roll-back
          duration: 900
          labels:
            severity: warning
          name: KubeDeploymentGenerationMismatch
          query: kube_deployment_status_observed_generation{job="integrations/kubernetes/kube-state-metrics"} != kube_deployment_metadata_generation{job="integrations/kubernetes/kube-state-metrics"}
          type: alerting
        - alerts: []
          annotations:
            description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 15 minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch
            summary: Deployment has not matched the expected number of replicas.
          duration: 900
          labels:
            severity: warning
          name: KubeDeploymentReplicasMismatch
          query: (kube_deployment_spec_replicas{job="integrations/kubernetes/kube-state-metrics"} > kube_deployment_status_replicas_available{job="integrations/kubernetes/kube-state-metrics"}) and (changes(kube_deployment_status_replicas_updated{job="integrations/kubernetes/kube-state-metrics"}[10m]) == 0)
          type: alerting
        - alerts: []
          annotations:
            description: Rollout of deployment {{ $labels.namespace }}/{{ $labels.deployment }} is not progressing for longer than 15 minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentrolloutstuck
            summary: Deployment rollout is not progressing.
          duration: 900
          labels:
            severity: warning
          name: KubeDeploymentRolloutStuck
          query: kube_deployment_status_condition{condition="Progressing",job="integrations/kubernetes/kube-state-metrics",status="false"} != 0
          type: alerting
        - alerts: []
          annotations:
            description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has not matched the expected number of replicas for longer than 15 minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetreplicasmismatch
            summary: StatefulSet has not matched the expected number of replicas.
          duration: 900
          labels:
            severity: warning
          name: KubeStatefulSetReplicasMismatch
          query: (kube_statefulset_status_replicas_ready{job="integrations/kubernetes/kube-state-metrics"} != kube_statefulset_status_replicas{job="integrations/kubernetes/kube-state-metrics"}) and (changes(kube_statefulset_status_replicas_updated{job="integrations/kubernetes/kube-state-metrics"}[10m]) == 0)
          type: alerting
        - alerts: []
          annotations:
            description: StatefulSet generation for {{ $labels.namespace }}/{{ $labels.statefulset }} does not match, this indicates that the StatefulSet has failed but has not been rolled back on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetgenerationmismatch
            summary: StatefulSet generation mismatch due to possible roll-back
          duration: 900
          labels:
            severity: warning
          name: KubeStatefulSetGenerationMismatch
          query: kube_statefulset_status_observed_generation{job="integrations/kubernetes/kube-state-metrics"} != kube_statefulset_metadata_generation{job="integrations/kubernetes/kube-state-metrics"}
          type: alerting
        - alerts: []
          annotations:
            description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} update has not been rolled out on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetupdatenotrolledout
            summary: StatefulSet update has not been rolled out.
          duration: 900
          labels:
            severity: warning
          name: KubeStatefulSetUpdateNotRolledOut
          query: (max by (namespace, statefulset, job, cluster) (kube_statefulset_status_current_revision{job="integrations/kubernetes/kube-state-metrics"} unless kube_statefulset_status_update_revision{job="integrations/kubernetes/kube-state-metrics"}) * (kube_statefulset_replicas{job="integrations/kubernetes/kube-state-metrics"} != kube_statefulset_status_replicas_updated{job="integrations/kubernetes/kube-state-metrics"})) and (changes(kube_statefulset_status_replicas_updated{job="integrations/kubernetes/kube-state-metrics"}[5m]) == 0)
          type: alerting
        - alerts:
            - annotations:
                description: DaemonSet duploservices-otel-o11y/duplo-monitoring-beyla has not finished or progressed for at least 15m on cluster duploinfra-o11y.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck
                summary: DaemonSet rollout is stuck.
              labels:
                alertname: KubeDaemonSetRolloutStuck
                cluster: duploinfra-o11y
                daemonset: duplo-monitoring-beyla
                instance: duplo-monitoring-kube-state-metrics.duploservices-otel-o11y.svc:8080
                job: integrations/kubernetes/kube-state-metrics
                namespace: duploservices-otel-o11y
                severity: warning
              value: "2e+00"
          annotations:
            description: DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} has not finished or progressed for at least 15m on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck
            summary: DaemonSet rollout is stuck.
          duration: 900
          labels:
            severity: warning
          name: KubeDaemonSetRolloutStuck
          query: ((kube_daemonset_status_current_number_scheduled{job="integrations/kubernetes/kube-state-metrics"} != kube_daemonset_status_desired_number_scheduled{job="integrations/kubernetes/kube-state-metrics"}) or (kube_daemonset_status_number_misscheduled{job="integrations/kubernetes/kube-state-metrics"} != 0) or (kube_daemonset_status_updated_number_scheduled{job="integrations/kubernetes/kube-state-metrics"} != kube_daemonset_status_desired_number_scheduled{job="integrations/kubernetes/kube-state-metrics"}) or (kube_daemonset_status_number_available{job="integrations/kubernetes/kube-state-metrics"} != kube_daemonset_status_desired_number_scheduled{job="integrations/kubernetes/kube-state-metrics"})) and (changes(kube_daemonset_status_updated_number_scheduled{job="integrations/kubernetes/kube-state-metrics"}[5m]) == 0)
          type: alerting
        - alerts: []
          annotations:
            description: 'pod/{{ $labels.pod }} in namespace {{ $labels.namespace }} on container {{ $labels.container}} has been in waiting state for longer than 1 hour. (reason: "{{ $labels.reason }}") on cluster {{ $labels.cluster }}.'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontainerwaiting
            summary: Pod container waiting longer than 1 hour
          duration: 3600
          labels:
            severity: warning
          name: KubeContainerWaiting
          query: kube_pod_container_status_waiting_reason{job="integrations/kubernetes/kube-state-metrics",reason!="CrashLoopBackOff"} > 0
          type: alerting
        - alerts: []
          annotations:
            description: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled on cluster {{ $labels.cluster }}.'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetnotscheduled
            summary: DaemonSet pods are not scheduled.
          duration: 600
          labels:
            severity: warning
          name: KubeDaemonSetNotScheduled
          query: kube_daemonset_status_desired_number_scheduled{job="integrations/kubernetes/kube-state-metrics"} - kube_daemonset_status_current_number_scheduled{job="integrations/kubernetes/kube-state-metrics"} > 0
          type: alerting
        - alerts: []
          annotations:
            description: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are running where they are not supposed to run on cluster {{ $labels.cluster }}.'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetmisscheduled
            summary: DaemonSet pods are misscheduled.
          duration: 900
          labels:
            severity: warning
          name: KubeDaemonSetMisScheduled
          query: kube_daemonset_status_number_misscheduled{job="integrations/kubernetes/kube-state-metrics"} > 0
          type: alerting
        - alerts: []
          annotations:
            description: Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than {{ "43200" | humanizeDuration }} to complete on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobnotcompleted
            summary: Job did not complete in time
          duration: 0
          labels:
            severity: warning
          name: KubeJobNotCompleted
          query: time() - max by (namespace, job_name, cluster) (kube_job_status_start_time{job="integrations/kubernetes/kube-state-metrics"} and kube_job_status_active{job="integrations/kubernetes/kube-state-metrics"} > 0) > 43200
          type: alerting
        - alerts: []
          annotations:
            description: Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete. Removing failed job after investigation should clear this alert on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed
            summary: Job failed to complete.
          duration: 900
          labels:
            severity: warning
          name: KubeJobFailed
          query: kube_job_failed{job="integrations/kubernetes/kube-state-metrics"} > 0
          type: alerting
        - alerts: []
          annotations:
            description: HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler  }} has not matched the desired number of replicas for longer than 15 minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubehpareplicasmismatch
            summary: HPA has not matched desired number of replicas.
          duration: 900
          labels:
            severity: warning
          name: KubeHpaReplicasMismatch
          query: (kube_horizontalpodautoscaler_status_desired_replicas{job="integrations/kubernetes/kube-state-metrics"} != kube_horizontalpodautoscaler_status_current_replicas{job="integrations/kubernetes/kube-state-metrics"}) and (kube_horizontalpodautoscaler_status_current_replicas{job="integrations/kubernetes/kube-state-metrics"} > kube_horizontalpodautoscaler_spec_min_replicas{job="integrations/kubernetes/kube-state-metrics"}) and (kube_horizontalpodautoscaler_status_current_replicas{job="integrations/kubernetes/kube-state-metrics"} < kube_horizontalpodautoscaler_spec_max_replicas{job="integrations/kubernetes/kube-state-metrics"}) and changes(kube_horizontalpodautoscaler_status_current_replicas{job="integrations/kubernetes/kube-state-metrics"}[15m]) == 0
          type: alerting
        - alerts: []
          annotations:
            description: HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler  }} has been running at max replicas for longer than 15 minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubehpamaxedout
            summary: HPA is running at max replicas
          duration: 900
          labels:
            severity: warning
          name: KubeHpaMaxedOut
          query: kube_horizontalpodautoscaler_status_current_replicas{job="integrations/kubernetes/kube-state-metrics"} == kube_horizontalpodautoscaler_spec_max_replicas{job="integrations/kubernetes/kube-state-metrics"}
          type: alerting
