apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: k8s.rules.pod_owner
    namespace: integrations-kubernetes
spec:
    rules:
        - name: namespace_workload_pod:kube_pod_owner:relabel
          labels:
            workload_type: deployment
          query: max by (cluster, namespace, workload, pod) (label_replace(label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="ReplicaSet"}, "replicaset", "$1", "owner_name", "(.*)") * on (replicaset, namespace, cluster) group_left (owner_name) topk by (replicaset, namespace, cluster) (1, max by (replicaset, namespace, owner_name, cluster) (kube_replicaset_owner{job="integrations/kubernetes/kube-state-metrics"})), "workload", "$1", "owner_name", "(.*)"))
          type: recording
        - name: namespace_workload_pod:kube_pod_owner:relabel
          labels:
            workload_type: daemonset
          query: max by (cluster, namespace, workload, pod) (label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="DaemonSet"}, "workload", "$1", "owner_name", "(.*)"))
          type: recording
        - name: namespace_workload_pod:kube_pod_owner:relabel
          labels:
            workload_type: statefulset
          query: max by (cluster, namespace, workload, pod) (label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="StatefulSet"}, "workload", "$1", "owner_name", "(.*)"))
          type: recording
        - name: namespace_workload_pod:kube_pod_owner:relabel
          labels:
            workload_type: job
          query: max by (cluster, namespace, workload, pod) (label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="Job"}, "workload", "$1", "owner_name", "(.*)"))
          type: recording
