{
 "title": "Duplo Windows CPU and system",
 "tags": [ "integration-duplo-windows-node" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace/Tenant",
    "query": {
     "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\", cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\", cluster=~\"$cluster\", namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg without (mode,core) (rate(windows_cpu_time_total{mode=\"idle\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg without (mode,core) (rate(windows_cpu_time_total{mode=\"idle\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU usage by modes",
   "type": "timeseries",
   "description": "CPU usage by different modes.\n",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance, mode) (irate(windows_cpu_time_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) \n/ on(instance) \ngroup_left sum by (instance) ((irate(windows_cpu_time_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))) * 100\n",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU average queue size",
   "type": "timeseries",
   "description": "The CPU average queue size in Windows, often referred to as the \"Processor Queue Length\" or \"CPU Queue Length,\" is a metric that measures the number of threads or tasks waiting to be processed by the central processing unit (CPU) at a given moment.\nIt is an essential performance indicator that reflects the workload and responsiveness of the CPU.\nWhen the CPU queue length is high, it indicates that there are more tasks in line for processing than the CPU can handle immediately.\n\nThis can lead to system slowdowns, decreased responsiveness, and potential performance issues. High CPU queue lengths are often associated with CPU saturation, where the CPU is struggling to keep up with the demands placed on it.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "windows_system_processor_queue_length{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}\n",
     "legendFormat": "CPU average queue"
    }
   ]
  },
  {
   "title": "Context switches/Interrupts",
   "type": "timeseries",
   "description": "Context switches occur when the operating system switches from running one process to another. Interrupts are signals sent to the CPU by external devices to request its attention.\n\nA high number of context switches or interrupts can indicate that the system is overloaded or that there are problems with specific devices or processes.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "irate(windows_system_context_switches_total{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "sum without (core) (irate(windows_cpu_interrupts_total{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Interrupts"
    }
   ]
  },
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Timezone",
   "type": "stat",
   "description": "Current system timezone.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_timezone{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}\nor ignoring(timezone)\nwindows_time_timezone{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Timezone"
    }
   ]
  },
  {
   "title": "NTP status",
   "type": "status-history",
   "description": "Status of time synchronization.",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 15 },
   "targets": [
    {
     "expr": "clamp_max(windows_time_ntp_client_time_sources{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}, 1)",
     "legendFormat": "NTP status"
    }
   ]
  },
  {
   "title": "NTP delay",
   "type": "timeseries",
   "description": "NTP trip delay: Total roundtrip delay experienced by the NTP client in receiving a response from the server for the most recent request,\nin seconds. This is the time elapsed on the NTP client between transmitting a request to the NTP server and receiving a valid response from the server.\n\nTime offset: Absolute time offset between the system clock and the chosen time source, in seconds.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "windows_time_ntp_round_trip_delay_seconds{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "NTP trip delay"
    },
    {
     "expr": "windows_time_computed_time_offset_seconds{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\", namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Time offset"
    }
   ]
  }
 ]
}