{
 "title": "Windows logs",
 "tags": [ "integration-windows-node" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({job=~\"integrations/windows_exporter\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({job=~\"integrations/windows_exporter\",cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\"}, instance)"
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": "label_values({job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}, channel)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "label_values({job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",channel=~\"$channel\"}, source)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",channel=~\"$channel\",source=~\"$source\"}, level)"
   },
   { "name": "regex_search", "label": "Regex search" },
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "stat",
   "description": "Shows if logs are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"integrations/windows.*\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"integrations/windows.*\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Logs volume grouped by \"level\" label.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",channel=~\"$channel\",source=~\"$source\",level=~\"$level\"}\n|~ \"$regex_search\"\n| json | __error__=``\n[$__interval]))\n",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\",channel=~\"$channel\",source=~\"$source\",level=~\"$level\"} \n|~ \"$regex_search\"\n| json | __error__=``\n| label_format timestamp=\"{{__timestamp__}}\"\n| drop channel_extracted,source_extracted,computer_extracted,level_extracted,keywords_extracted\n| line_format `{{ if eq \"[[instance]]\" \".*\" }}{{ alignLeft 25 .instance}}|{{end}}{{alignLeft 12 .channel }}| {{ alignLeft 25 .source}}| {{ .message }}`\n\n"
    }
   ]
  }
 ]
}