{
 "title": "SLO Overview",
 "tags": [ "slo-overview" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Above Target (1 day)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1d",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_success_rate_5m < 1e308)[1d:5m]))\n\t\t  / sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_total_rate_5m < 1e308)[1d:5m]))\n\t\t  # combine with series that aren't producing duplo_slo_success_rate_5m and duplo_slo_total_rate_5m\n\t\t  or avg by (duplo_slo_uuid) (duplo_slo_sli_1d)\n\t\t)\n\t\t> on(duplo_slo_uuid) duplo_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Above Target (6 hour)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 6h",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_success_rate_5m < 1e308)[6h:5m]))\n\t\t  / sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_total_rate_5m < 1e308)[6h:5m]))\n\t\t  # combine with series that aren't producing duplo_slo_success_rate_5m and duplo_slo_total_rate_5m\n\t\t  or avg by (duplo_slo_uuid) (duplo_slo_sli_6h)\n\t\t)\n\t\t> on(duplo_slo_uuid) duplo_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Above Target (1 hour)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1h",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_success_rate_5m < 1e308)[1h:5m]))\n\t\t  / sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_total_rate_5m < 1e308)[1h:5m]))\n\t\t  # combine with series that aren't producing duplo_slo_success_rate_5m and duplo_slo_total_rate_5m\n\t\t  or avg by (duplo_slo_uuid) (duplo_slo_sli_1h)\n\t\t)\n\t\t> on(duplo_slo_uuid) duplo_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLOs Defined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SLOs Recording",
   "type": "stat",
   "description": "The number of SLOs that are recording values",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (duplo_slo_uuid)(duplo_slo_sli_5m)) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recorded SLI Series",
   "type": "stat",
   "description": "The total number of series created by SLO recording rules.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"duplo_slo_.*\", duplo_slo_uuid!=\"\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "Create SLO with hyperlink to the Manage SLO dashboard",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 110px; font-family: Arial, sans-serif;\">\r\n    <a href=\"/d/manage-slo/manage-slo?var-duplo_uuid=\" \r\n       style=\"display: inline-block; padding: 15px 30px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px; font-size: 20px;\">\r\n        Create SLO\r\n    </a>\r\n</div>"
   },
   "targets": [
    {}
   ]
  }
 ]
}