apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kubernetes-windows-node-0
    namespace: integrations-kubernetes-windows
spec:
    rules:
        - labels: {}
          name: node:windows_node:sum
          query: count by (cluster) (windows_system_system_up_time{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: node:windows_node_num_cpu:sum
          query: count by (cluster, instance) (sum by (cluster, instance, core) (windows_cpu_time_total{job="integrations/windows_exporter"}))
          type: recording
        - labels: {}
          name: :windows_node_cpu_utilisation:avg1m
          query: 1 - avg by (cluster) (rate(windows_cpu_time_total{job="integrations/windows_exporter",mode="idle"}[1m]))
          type: recording
        - labels: {}
          name: node:windows_node_cpu_utilisation:avg1m
          query: 1 - avg by (cluster, instance) (rate(windows_cpu_time_total{job="integrations/windows_exporter",mode="idle"}[1m]))
          type: recording
        - labels: {}
          name: ':windows_node_memory_utilisation:'
          query: 1 - sum by (cluster) (windows_memory_available_bytes{job="integrations/windows_exporter"}) / sum by (cluster) (windows_os_visible_memory_bytes{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: :windows_node_memory_MemFreeCached_bytes:sum
          query: sum by (cluster) (windows_memory_available_bytes{job="integrations/windows_exporter"} + windows_memory_cache_bytes{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: node:windows_node_memory_totalCached_bytes:sum
          query: (windows_memory_cache_bytes{job="integrations/windows_exporter"} + windows_memory_modified_page_list_bytes{job="integrations/windows_exporter"} + windows_memory_standby_cache_core_bytes{job="integrations/windows_exporter"} + windows_memory_standby_cache_normal_priority_bytes{job="integrations/windows_exporter"} + windows_memory_standby_cache_reserve_bytes{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: :windows_node_memory_MemTotal_bytes:sum
          query: sum by (cluster) (windows_os_visible_memory_bytes{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: node:windows_node_memory_bytes_available:sum
          query: sum by (cluster, instance) ((windows_memory_available_bytes{job="integrations/windows_exporter"}))
          type: recording
        - labels: {}
          name: node:windows_node_memory_bytes_total:sum
          query: sum by (cluster, instance) (windows_os_visible_memory_bytes{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: node:windows_node_memory_utilisation:ratio
          query: (node:windows_node_memory_bytes_total:sum - node:windows_node_memory_bytes_available:sum) / scalar(sum by (cluster) (node:windows_node_memory_bytes_total:sum))
          type: recording
        - labels: {}
          name: 'node:windows_node_memory_utilisation:'
          query: 1 - (node:windows_node_memory_bytes_available:sum / node:windows_node_memory_bytes_total:sum)
          type: recording
        - labels: {}
          name: node:windows_node_memory_swap_io_pages:irate
          query: irate(windows_memory_swap_page_operations_total{job="integrations/windows_exporter"}[5m])
          type: recording
        - labels: {}
          name: :windows_node_disk_utilisation:avg_irate
          query: avg by (cluster) (irate(windows_logical_disk_read_seconds_total{job="integrations/windows_exporter"}[1m]) + irate(windows_logical_disk_write_seconds_total{job="integrations/windows_exporter"}[1m]))
          type: recording
        - labels: {}
          name: node:windows_node_disk_utilisation:avg_irate
          query: avg by (cluster, instance) ((irate(windows_logical_disk_read_seconds_total{job="integrations/windows_exporter"}[1m]) + irate(windows_logical_disk_write_seconds_total{job="integrations/windows_exporter"}[1m])))
          type: recording
        - labels: {}
          name: 'node:windows_node_filesystem_usage:'
          query: max by (cluster, instance, volume) ((windows_logical_disk_size_bytes{job="integrations/windows_exporter"} - windows_logical_disk_free_bytes{job="integrations/windows_exporter"}) / windows_logical_disk_size_bytes{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: 'node:windows_node_filesystem_avail:'
          query: max by (cluster, instance, volume) (windows_logical_disk_free_bytes{job="integrations/windows_exporter"} / windows_logical_disk_size_bytes{job="integrations/windows_exporter"})
          type: recording
        - labels: {}
          name: :windows_node_net_utilisation:sum_irate
          query: sum by (cluster) (irate(windows_net_bytes_total{job="integrations/windows_exporter"}[1m]))
          type: recording
        - labels: {}
          name: node:windows_node_net_utilisation:sum_irate
          query: sum by (cluster, instance) ((irate(windows_net_bytes_total{job="integrations/windows_exporter"}[1m])))
          type: recording
        - labels: {}
          name: :windows_node_net_saturation:sum_irate
          query: sum by (cluster) (irate(windows_net_packets_received_discarded_total{job="integrations/windows_exporter"}[1m])) + sum by (cluster) (irate(windows_net_packets_outbound_discarded_total{job="integrations/windows_exporter"}[1m]))
          type: recording
          