apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
    name: Integration-Loki.log-alerts
spec:
    folderUid: integration-loki
    interval: 60
    rules:
        - annotations:
            description: |-
                Loki is throttling logs in cluster {{ $labels.cluster }}, namespace {{ $labels.namespace }} due to ingestion rate limits. Reduce log volume or adjust limits.
            summary: 'Loki ingestion rate limit exceeded in {{ $labels.cluster }}/{{ $labels.namespace }}'
          condition: C
          data:
            - datasourceUid: duplo-logging
              model:
                datasource:
                    type: loki
                    uid: duplo-logging
                editorMode: code
                expr: sum(count_over_time({container="loki"} |~ "(?i)rate limit" | json | logfmt | drop __error__, __error_details__ | caller=~".*manager.go.*" | msg="write operation failed" [$__auto])) by (cluster, namespace)
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
              queryType: instant
              refId: A
              relativeTimeRange:
                from: 900
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
              refId: C
              relativeTimeRange: {}
          execErrState: Error
          folderUID: integration-loki
          for: 0s
          labels:
            severity: warning
            owner: duplo
          noDataState: OK
          orgID: 1
          ruleGroup: log-alerts
          title: LokiRateLimitAlert
          uid: Lokiratelimitalert
    title: log-alerts