apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: microsoft-iis
    namespace: integrations-microsoft-iis
spec:
    rules:
        - alerts: []
          annotations:
            description: |
                The number of rejected async IO requests is {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} - {{ $labels.site }} which is above the threshold of 20.
            summary: There are a high number of rejected async I/O requests for a site.
          duration: 300
          labels:
            severity: warning
          name: MicrosoftIISHighNumberOfRejectedAsyncIORequests
          query: increase(windows_iis_rejected_async_io_requests_total[5m]) > 20
          type: alerting
        - alerts: []
          annotations:
            description: |
                The number of 5xx request errors is {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} - {{ $labels.app }} which is above the threshold of 5.
            summary: There are a high number of 5xx request errors for an application.
          duration: 300
          labels:
            severity: critical
          name: MicrosoftIISHighNumberOf5xxRequestErrors
          query: sum without (pid, status_code) (increase(windows_iis_worker_request_errors_total{status_code=~"5.*"}[5m])) > 5
          type: alerting
        - alerts: []
          annotations:
            description: |
                The success rate for websocket connections is {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} - {{ $labels.app }} which is above the threshold of 80.
            summary: There is a low success rate for websocket connections for an application.
          duration: 300
          labels:
            severity: critical
          name: MicrosoftIISLowSuccessRateForWebsocketConnections
          query: sum without (pid) (increase(windows_iis_worker_websocket_connection_accepted_total[5m]) / clamp_min(increase(windows_iis_worker_websocket_connection_attempts_total[5m]), 1)) * 100 > 80
          type: alerting
        - alerts: []
          annotations:
            description: |
                The threadpool utilization is at {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} - {{ $labels.app }} which is above the threshold of 90.
            summary: The thread pool utilization is nearing max capacity.
          duration: 300
          labels:
            severity: critical
          name: MicrosoftIISThreadpoolUtilizationNearingMax
          query: sum without (pid, state) (windows_iis_worker_threads / windows_iis_worker_max_threads) * 100 > 90
          type: alerting
        - alerts: []
          annotations:
            description: |
                The number of worker process failures is at {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} - {{ $labels.app }} which is above the threshold of 10.
            summary: There are a high number of worker process failures for an application.
          duration: 300
          labels:
            severity: warning
          name: MicrosoftIISHighNumberOfWorkerProcessFailures
          query: increase(windows_iis_total_worker_process_failures[5m]) > 10
          type: alerting
