apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-scripts
  namespace: duploservices-otel-o11y
data:
  entrypoint.sh: |
    #!/bin/bash
    set -e

    # Install git if not present (depending on base image)
    if ! command -v git &> /dev/null; then
        apt-get update && apt-get install -y git
    fi

    # Clone/pull the latest version of the script
    REPO_URL="https://github.com/duplocloud/opentelemetry-release.git"
    SCRIPT_PATH="otel-observability.py"

    if [ -d "opentelemetry-release" ]; then
        cd opentelemetry-release
        git pull
    else
        git clone $REPO_URL opentelemetry-release
        git checkout observability
        git pull
        cd opentelemetry-release
    fi

    cd observability

    # Install requirements
    pip install -r requirements.txt

    # Run the script
    python $SCRIPT_PATH 