apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kubelet.rules
    namespace: integrations-kubernetes
spec:
    rules:
        - labels:
            quantile: "0.99"
          name: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
          query: histogram_quantile(0.99, sum by (cluster, instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket{job="integrations/kubernetes/kubelet"}[5m])) * on (cluster, instance) group_left (node) kubelet_node_name{job="integrations/kubernetes/kubelet"})
          type: recording
        - labels:
            quantile: "0.9"
          name: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
          query: histogram_quantile(0.9, sum by (cluster, instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket{job="integrations/kubernetes/kubelet"}[5m])) * on (cluster, instance) group_left (node) kubelet_node_name{job="integrations/kubernetes/kubelet"})
          type: recording
        - labels:
            quantile: "0.5"
          name: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
          query: histogram_quantile(0.5, sum by (cluster, instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket{job="integrations/kubernetes/kubelet"}[5m])) * on (cluster, instance) group_left (node) kubelet_node_name{job="integrations/kubernetes/kubelet"})
          type: recording
