apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kube-apiserver-histogram.rules
    namespace: integrations-kubernetes
spec:
    rules:
        - labels:
            quantile: "0.99"
            verb: read
          name: cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile
          query: histogram_quantile(0.99, sum by (cluster, le, resource) (rate(apiserver_request_sli_duration_seconds_bucket{job="integrations/kubernetes/kube-apiserver",subresource!~"proxy|attach|log|exec|portforward",verb=~"LIST|GET"}[5m]))) > 0
          type: recording
        - labels:
            quantile: "0.99"
            verb: write
          name: cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile
          query: histogram_quantile(0.99, sum by (cluster, le, resource) (rate(apiserver_request_sli_duration_seconds_bucket{job="integrations/kubernetes/kube-apiserver",subresource!~"proxy|attach|log|exec|portforward",verb=~"POST|PUT|PATCH|DELETE"}[5m]))) > 0
          type: recording
