apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: controller-manager-alerts
    namespace: integrations-kubernetes-system
spec:
    rules:
        - alerts:
            - annotations:
                description: KubeControllerManager has disappeared from Prometheus target discovery.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
                summary: Target disappeared from Prometheus target discovery.
              labels:
                alertname: KubeControllerManagerDown
                severity: critical
              value: "1e+00"
          annotations:
            description: KubeControllerManager has disappeared from Prometheus target discovery.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
            summary: Target disappeared from Prometheus target discovery.
          duration: 900
          labels:
            severity: critical
          name: KubeControllerManagerDown
          query: absent(up{job="integrations/kubernetes/kube-controller-manager"} == 1)
          type: alerting
