apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: scheduler-alerts
    namespace: integrations-kubernetes-system
spec:
    rules:
        - alerts:
            - annotations:
                description: KubeScheduler has disappeared from Prometheus target discovery.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeschedulerdown
                summary: Target disappeared from Prometheus target discovery.
              labels:
                alertname: KubeSchedulerDown
                severity: critical
              value: "1e+00"
          annotations:
            description: KubeScheduler has disappeared from Prometheus target discovery.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeschedulerdown
            summary: Target disappeared from Prometheus target discovery.
          duration: 900
          labels:
            severity: critical
          name: KubeSchedulerDown
          query: absent(up{job="integrations/kubernetes/kube-scheduler"} == 1)
          type: alerting
