apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kube-apiserver-slos
    namespace: integrations-kubernetes-apiserver
spec:
    rules:
        - alerts: []
          annotations:
            description: The API server is burning too much error budget on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
            summary: The API server is burning too much error budget.
          duration: 120
          labels:
            long: 1h
            severity: critical
            short: 5m
          name: KubeAPIErrorBudgetBurn
          query: sum by (cluster) (apiserver_request:burnrate1h) > (14.4 * 0.01) and on (cluster) sum by (cluster) (apiserver_request:burnrate5m) > (14.4 * 0.01)
          type: alerting
        - alerts: []
          annotations:
            description: The API server is burning too much error budget on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
            summary: The API server is burning too much error budget.
          duration: 900
          labels:
            long: 6h
            severity: critical
            short: 30m
          name: KubeAPIErrorBudgetBurn
          query: sum by (cluster) (apiserver_request:burnrate6h) > (6 * 0.01) and on (cluster) sum by (cluster) (apiserver_request:burnrate30m) > (6 * 0.01)
          type: alerting
        - alerts: []
          annotations:
            description: The API server is burning too much error budget on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
            summary: The API server is burning too much error budget.
          duration: 3600
          labels:
            long: 1d
            severity: warning
            short: 2h
          name: KubeAPIErrorBudgetBurn
          query: sum by (cluster) (apiserver_request:burnrate1d) > (3 * 0.01) and on (cluster) sum by (cluster) (apiserver_request:burnrate2h) > (3 * 0.01)
          type: alerting
        - alerts: []
          annotations:
            description: The API server is burning too much error budget on cluster {{ $labels.cluster }}.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
            summary: The API server is burning too much error budget.
          duration: 10800
          labels:
            long: 3d
            severity: warning
            short: 6h
          name: KubeAPIErrorBudgetBurn
          query: sum by (cluster) (apiserver_request:burnrate3d) > (1 * 0.01) and on (cluster) sum by (cluster) (apiserver_request:burnrate6h) > (1 * 0.01)
          type: alerting
