apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kube-apiserver-availability.rules
    namespace: integrations-kubernetes-apiserver
spec:
    rules:
        - labels: {}
          name: code_verb:apiserver_request_total:increase30d
          query: avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24 * 30
          type: recording
        - labels:
            verb: read
          name: code:apiserver_request_total:increase30d
          query: sum by (cluster, code) (code_verb:apiserver_request_total:increase30d{verb=~"LIST|GET"})
          type: recording
        - labels:
            verb: write
          name: code:apiserver_request_total:increase30d
          query: sum by (cluster, code) (code_verb:apiserver_request_total:increase30d{verb=~"POST|PUT|PATCH|DELETE"})
          type: recording
        - labels: {}
          name: cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h
          query: sum by (cluster, verb, scope, le) (increase(apiserver_request_sli_duration_seconds_bucket[1h]))
          type: recording
        - labels: {}
          name: cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d
          query: sum by (cluster, verb, scope, le) (avg_over_time(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h[30d]) * 24 * 30)
          type: recording
        - labels: {}
          name: cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase1h
          query: sum by (cluster, verb, scope) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h{le="+Inf"})
          type: recording
        - labels: {}
          name: cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d
          query: sum by (cluster, verb, scope) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le="+Inf"})
          type: recording
        - labels:
            verb: all
          name: apiserver_request:availability30d
          query: 1 - ((sum by (cluster) (cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"}) - sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"1(\\.0)?",verb=~"POST|PUT|PATCH|DELETE"})) + (sum by (cluster) (cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"LIST|GET"}) - ((sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"1(\\.0)?",scope=~"resource|",verb=~"LIST|GET"}) or vector(0)) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"5(\\.0)?",scope="namespace",verb=~"LIST|GET"}) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"30(\\.0)?",scope="cluster",verb=~"LIST|GET"}))) + sum by (cluster) (code:apiserver_request_total:increase30d{code=~"5.."} or vector(0))) / sum by (cluster) (code:apiserver_request_total:increase30d)
          type: recording
        - labels:
            verb: read
          name: apiserver_request:availability30d
          query: 1 - (sum by (cluster) (cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"LIST|GET"}) - ((sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"1(\\.0)?",scope=~"resource|",verb=~"LIST|GET"}) or vector(0)) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"5(\\.0)?",scope="namespace",verb=~"LIST|GET"}) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"30(\\.0)?",scope="cluster",verb=~"LIST|GET"})) + sum by (cluster) (code:apiserver_request_total:increase30d{code=~"5..",verb="read"} or vector(0))) / sum by (cluster) (code:apiserver_request_total:increase30d{verb="read"})
          type: recording
        - labels:
            verb: write
          name: apiserver_request:availability30d
          query: 1 - ((sum by (cluster) (cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"}) - sum by (cluster) (cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le=~"1(\\.0)?",verb=~"POST|PUT|PATCH|DELETE"})) + sum by (cluster) (code:apiserver_request_total:increase30d{code=~"5..",verb="write"} or vector(0))) / sum by (cluster) (code:apiserver_request_total:increase30d{verb="write"})
          type: recording
        - labels:
            verb: read
          name: code_resource:apiserver_request_total:rate5m
          query: sum by (cluster, code, resource) (rate(apiserver_request_total{job="integrations/kubernetes/kube-apiserver",verb=~"LIST|GET"}[5m]))
          type: recording
        - labels:
            verb: write
          name: code_resource:apiserver_request_total:rate5m
          query: sum by (cluster, code, resource) (rate(apiserver_request_total{job="integrations/kubernetes/kube-apiserver",verb=~"POST|PUT|PATCH|DELETE"}[5m]))
          type: recording
        - labels: {}
          name: code_verb:apiserver_request_total:increase1h
          query: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"2..",job="integrations/kubernetes/kube-apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
          type: recording
        - labels: {}
          name: code_verb:apiserver_request_total:increase1h
          query: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"3..",job="integrations/kubernetes/kube-apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
          type: recording
        - labels: {}
          name: code_verb:apiserver_request_total:increase1h
          query: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"4..",job="integrations/kubernetes/kube-apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
          type: recording
        - labels: {}
          name: code_verb:apiserver_request_total:increase1h
          query: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"5..",job="integrations/kubernetes/kube-apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
          type: recording
