apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: kube-proxy-alerts
    namespace: integrations-kubernetes-system
spec:
    rules:
        - alerts:
            - annotations:
                description: KubeProxy has disappeared from Prometheus target discovery.
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeproxydown
                summary: Target disappeared from Prometheus target discovery.
              labels:
                alertname: KubeProxyDown
                severity: critical
              value: "1e+00"
          annotations:
            description: KubeProxy has disappeared from Prometheus target discovery.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeproxydown
            summary: Target disappeared from Prometheus target discovery.
          duration: 900
          labels:
            severity: critical
          name: KubeProxyDown
          query: absent(up{job="integrations/kubernetes/kube-proxy"} == 1)
          type: alerting
