{
 "title": "AWS Redshift",
 "description": "Visualize AWS Redshift metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "clusteridentifier",
    "label": "ClusterIdentifier",
    "query": "dimension_values($region,AWS/Redshift,CPUUtilization,ClusterIdentifier) "
   },
   {
    "name": "nodeid",
    "label": "NodeID",
    "query": "dimension_values($region,AWS/Redshift,ReadIOPS,NodeID)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization/DatabaseConnections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MaintenanceMode/HealthStatus",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MaintenanceMode",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthStatus",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadIOPS/WriteIOPS - NodeId: $nodeid",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier", "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier", "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadLatency/WriteLatency - NodeId: $nodeid",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier", "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadLatency",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier", "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteLatency",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadThroughput/WriteThroughput - NodeId: $nodeid",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier", "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ClusterIdentifier": "$clusteridentifier", "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}