{
 "title": "AWS ECS",
 "description": "Visualize AWS ECS metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {}
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MemoryUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPUReservation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "CPUReservation",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MemoryReservation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "MemoryReservation",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}