apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
    name: Integration-Kubernetes.pod-alerts
spec:
    folderUid: duplo-common
    interval: 60
    rules:
        - annotations:
            description: 'The pod `{{ $labels.pod }}` in namespace `{{ $labels.namespace }}` (cluster: `{{ $labels.cluster }}`) experienced an OOMKilled event.'
            summary: OOMKilled pod detected in {{ $labels.namespace }}/{{ $labels.pod }}
          condition: C
          data:
            - datasourceUid: duplo-metrics
              model:
                datasource:
                    type: prometheus
                    uid: duplo-metrics
                editorMode: code
                exemplar: false
                expr: sum by (pod, cluster, namespace) (kube_pod_container_status_terminated_reason{reason="OOMKilled"})>0
                format: time_series
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
              refId: A
              relativeTimeRange:
                from: 900
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
              refId: C
              relativeTimeRange: {}
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
              refId: B
              relativeTimeRange: {}
          execErrState: Error
          folderUID: duplo-common
          for: 1m0s
          noDataState: NoData
          orgID: 1
          ruleGroup: Pod-alerts
          title: Pod OOM Alert
          uid: PodOOMalert
    title: Pod alerts