apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertNotificationPolicy
metadata:
  name: global
spec:
  group_by:
    - grafana_folder
    - alertname
  receiver: grafana-default-email
  orgId: 1
  routes:
    - object_matchers:
        - - tenant
          - =~
          - .*otel.*
      receiver: duplo-slack
    - object_matchers:
        - - namespace
          - =~
          - .*otel.*
      receiver: duplo-slack
    - object_matchers:
        - - label_tenantname
          - =~
          - .*otel.*
      receiver: duplo-slack
    - object_matchers:
        - - pod
          - =~
          - .*monitoring-prometheus-node-exporter.*
      receiver: duplo-slack
    - object_matchers:
        - - pod
          - =~
          - .*monitoring-alloy-.*
      receiver: duplo-slack
    - object_matchers:
        - - pod
          - =~
          - .*monitoring-beyla.*
      receiver: duplo-slack