{
 "title": "JVM Runtime",
 "description": "JVM Runtime details (CPU, Threads, Classloading, File Descriptors, Logs)",
 "tags": [
  "jvm",
  "java",
  "runtime"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Job",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU & Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(job,instance)({__name__=~\"process_cpu_usage|jvm_cpu_recent_utilization_ratio|process_runtime_jvm_cpu_utilization_ratio\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} process"
    },
    {
     "expr": "avg by(job,instance)({__name__=~\"system_cpu_usage|system_cpu_utilization_ratio|process_runtime_jvm_system_cpu_utilization_ratio\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} system"
    },
    {
     "expr": "avg_over_time(({__name__=~\"process_cpu_usage|jvm_cpu_recent_utilization_ratio|process_runtime_jvm_cpu_utilization_ratio\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})[15m:])",
     "legendFormat": "{{instance}} avg 15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(job,instance)({__name__=~\"system_load_average_1m|process_runtime_jvm_system_cpu_load_1m\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} load 1m"
    },
    {
     "expr": "avg by(job,instance)({__name__=~\"system_cpu_count|jvm_cpu_count\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} processors"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(job,instance)({__name__=~\"jvm_threads_live|jvm_thread_count|process_runtime_jvm_threads_count\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} live"
    },
    {
     "expr": "avg by(job,instance)({__name__=~\"jvm_threads_daemon\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} daemon"
    },
    {
     "expr": "avg by(job,instance)({__name__=~\"jvm_threads_peak\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} peak"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state)({__name__=~\"jvm_threads_states\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"process_files_open|process_open_fds|process_open_file_descriptor_count\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"}",
     "legendFormat": "{{instance}} open"
    },
    {
     "expr": "{__name__=~\"process_files_max|process_max_fds\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"}[1m])",
     "legendFormat": "{{instance}} {{level}}"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(job,instance)({__name__=~\"jvm_classes_loaded|jvm_class_count|process_runtime_jvm_classes_current_loaded\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Class Delta",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(({__name__=~\"jvm_classes_loaded|jvm_class_count|process_runtime_jvm_classes_current_loaded\", cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})[1m:])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}