{
 "title": "JVM Memory",
 "description": "JVM Memory details dashboard for Micrometer instrumented applications",
 "tags": [
  "jvm",
  "java",
  "memory"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Job",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\"}, instance)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", job=\"$application\", area=\"heap\"}, id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", job=\"$application\", area=\"nonheap\"}, id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{cluster=\"$cluster\", job=\"$application\"}, id)"
   }
  ]
 },
 "panels": [
  { "title": "JVM Memory Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job,instance)(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", area=\"heap\"})",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "avg by(job,instance)(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", area=\"heap\"})",
     "legendFormat": "{{instance}} committed"
    },
    {
     "expr": "avg by(job,instance)(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", area=\"heap\"})",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job,instance)(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "avg by(job,instance)(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "{{instance}} committed"
    },
    {
     "expr": "avg by(job,instance)(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Total Memory (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job,instance)(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "sum by(job,instance)(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} committed"
    },
    {
     "expr": "sum by(job,instance)(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{instance}} used"
      },
      {
       "expr": "jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{instance}} committed"
      },
      {
       "expr": "jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{instance}} max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{instance}} used"
      },
      {
       "expr": "jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{instance}} committed"
      },
      {
       "expr": "jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{instance}} max"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_buffer_pool",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "repeat": "jvm_buffer_pool",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "{{instance}} used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "{{instance}} capacity"
      },
      {
       "expr": "jvm_buffer_count_buffers{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "{{instance}} count"
      }
     ]
    }
   ]
  },
  {
   "title": "GC Generation Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space (Young Gen)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(job,instance)(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1|PS|Par )?Eden Space\", area=\"heap\"})",
       "legendFormat": "{{instance}} used"
      },
      {
       "expr": "avg by(job,instance)(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1|PS|Par )?Eden Space\", area=\"heap\"})",
       "legendFormat": "{{instance}} committed"
      },
      {
       "expr": "avg by(job,instance)(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1|PS|Par )?Eden Space\", area=\"heap\"})",
       "legendFormat": "{{instance}} max"
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(job,instance)(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1|PS|Par )?Survivor Space\", area=\"heap\"})",
       "legendFormat": "{{instance}} used"
      },
      {
       "expr": "avg by(job,instance)(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1|PS|Par )?Survivor Space\", area=\"heap\"})",
       "legendFormat": "{{instance}} committed"
      },
      {
       "expr": "avg by(job,instance)(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1|PS|Par )?Survivor Space\", area=\"heap\"})",
       "legendFormat": "{{instance}} max"
      }
     ]
    },
    {
     "title": "Old Gen / Tenured Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(job,instance)(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1 Old Gen|PS Old Gen|Tenured Gen|CMS Old Gen)\", area=\"heap\"})",
       "legendFormat": "{{instance}} used"
      },
      {
       "expr": "avg by(job,instance)(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1 Old Gen|PS Old Gen|Tenured Gen|CMS Old Gen)\", area=\"heap\"})",
       "legendFormat": "{{instance}} committed"
      },
      {
       "expr": "avg by(job,instance)(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", job=\"$application\", instance=~\"$pod\", id=~\"(G1 Old Gen|PS Old Gen|Tenured Gen|CMS Old Gen)\", area=\"heap\"})",
       "legendFormat": "{{instance}} max"
      }
     ]
    }
   ]
  }
 ]
}