{
 "title": "JVM Overview",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "tags": [
  "jvm",
  "java",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "application",
    "label": "Job",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", instance=~\"($namespace)\\\\..+\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", job=\"$application\", instance=~\"($namespace)\\\\..+\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_uptime_seconds{cluster=\"$cluster\", job=\"$application\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time_seconds{cluster=\"$cluster\", job=\"$application\"})*1000"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", job=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{cluster=\"$cluster\", job=\"$application\", area=\"heap\"}) or sum(jvm_memory_used_bytes{cluster=\"$cluster\", job=\"$application\", jvm_memory_type=\"heap\"})*100/clamp_min(sum(jvm_memory_limit_bytes{cluster=\"$cluster\", job=\"$application\", jvm_memory_type=\"heap\"}),1) or sum(process_runtime_jvm_memory_usage_bytes{cluster=\"$cluster\", job=\"$application\", type=\"heap\"})*100/sum(process_runtime_jvm_memory_limit_bytes{cluster=\"$cluster\", job=\"$application\", type=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", job=\"$application\", area=\"nonheap\"})*100/clamp_min(sum(jvm_memory_max_bytes{cluster=\"$cluster\", job=\"$application\", area=\"nonheap\"}),1) or sum(jvm_memory_used_bytes{cluster=\"$cluster\", job=\"$application\", jvm_memory_type=\"non_heap\"})*100/clamp_min(sum(jvm_memory_limit_bytes{cluster=\"$cluster\", job=\"$application\", jvm_memory_type=\"non_heap\"}),1) or sum(process_runtime_jvm_memory_usage_bytes{cluster=\"$cluster\", job=\"$application\", type=\"nonheap\"})*100/clamp_min(sum(process_runtime_jvm_memory_limit_bytes{cluster=\"$cluster\", job=\"$application\", type=\"nonheap\"}),1)"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", job=\"$application\", status=~\"5..\"}[2m])) or sum(rate(http_server_request_duration_seconds_count{cluster=\"$cluster\", job=\"$application\", http_response_status_code=~\"5..\"}[2m])) or sum(rate(http_server_duration_milliseconds_count{cluster=\"$cluster\", job=\"$application\", http_status_code=~\"5..\"}[2m]))"
    }
   ]
  },
  {
   "title": "HTTP Latency Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(http_server_requests_max_seconds{cluster=\"$cluster\", job=\"$application\"}) or histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$application\"}[2m]))))*1000"
    }
   ]
  },
  {
   "title": "CPU Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"process_cpu_usage|jvm_cpu_recent_utilization_ratio|process_runtime_jvm_cpu_utilization_ratio\", cluster=\"$cluster\", job=\"$application\"})*100"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum by(job,instance)(rate({__name__=~\"jvm_gc_pause_seconds_sum|jvm_gc_duration_seconds_sum|process_runtime_jvm_gc_duration_seconds_sum\", cluster=\"$cluster\", job=\"$application\"}[2m])) / on(job,instance) {__name__=~\"system_cpu_count|jvm_cpu_count\", cluster=\"$cluster\", job=\"$application\"})*100"
    }
   ]
  },
  {
   "title": "Max Live Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"jvm_threads_live|jvm_thread_count|process_runtime_jvm_threads_count\", cluster=\"$cluster\", job=\"$application\"})"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"jvm_threads_states\", cluster=\"$cluster\", job=\"$application\", state=\"blocked\"}) or sum(jvm_thread_count{cluster=\"$cluster\", job=\"$application\", jvm_thread_state=\"BLOCKED\"})"
    }
   ]
  },
  {
   "title": "Max Open FDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"process_files_open|process_open_fds|process_open_file_descriptor_count\", cluster=\"$cluster\", job=\"$application\"})"
    }
   ]
  },
  {
   "title": "Error Logs /min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{cluster=\"$cluster\", job=\"$application\", level=\"error\"}[2m]))*60"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", job=\"$application\"}[1m])) or sum(rate(http_server_request_duration_seconds_count{cluster=\"$cluster\", job=\"$application\"}[1m])) or sum(rate(http_server_duration_milliseconds_count{cluster=\"$cluster\", job=\"$application\"}[1m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", job=\"$application\", status=~\"5..\"}[1m])) or sum(rate(http_server_request_duration_seconds_count{cluster=\"$cluster\", job=\"$application\", http_response_status_code=~\"5..\"}[1m])) or sum(rate(http_server_duration_milliseconds_count{cluster=\"$cluster\", job=\"$application\", http_status_code=~\"5..\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{cluster=\"$cluster\", job=\"$application\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", job=\"$application\", status!~\"5..\"}[1m])) or sum(rate(http_server_request_duration_seconds_sum{cluster=\"$cluster\", job=\"$application\", http_response_status_code!~\"5..\"}[1m]))/sum(rate(http_server_request_duration_seconds_count{cluster=\"$cluster\", job=\"$application\", http_response_status_code!~\"5..\"}[1m])) or sum(rate(http_server_duration_milliseconds_sum{cluster=\"$cluster\", job=\"$application\", http_status_code!~\"5..\"}[1m]))/sum(rate(http_server_duration_milliseconds_count{cluster=\"$cluster\", job=\"$application\", http_status_code!~\"5..\"}[1m]))/1000",
     "legendFormat": "Average"
    },
    {
     "expr": "max(http_server_requests_max_seconds{cluster=\"$cluster\", job=\"$application\", status!~\"5..\"}) or histogram_quantile(0.99, sum by(le)(rate(http_server_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$application\", http_response_status_code!~\"5..\"}[1m]))) or histogram_quantile(0.99, sum by(le)(rate(http_server_duration_milliseconds_bucket{cluster=\"$cluster\", job=\"$application\", http_status_code!~\"5..\"}[1m])))/1000",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread Pool / Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{__name__=~\"executor_active_threads\", cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"}",
     "legendFormat": "{{instance}} busy"
    },
    {
     "expr": "{__name__=~\"executor_pool_size_threads\", cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"}",
     "legendFormat": "{{instance}} current"
    },
    {
     "expr": "{__name__=~\"executor_pool_max_threads\", cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "DB Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job,instance)(db_client_connection_count{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "sum by(job,instance)(db_client_connection_max{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} max"
    },
    {
     "expr": "sum by(job,instance)(db_client_connection_idle_min{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} idle min"
    },
    {
     "expr": "sum by(job,instance)(db_client_connection_pending_requests{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"})",
     "legendFormat": "{{instance}} pending"
    }
   ]
  },
  {
   "title": "DB Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(db_client_operation_duration_seconds_sum{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"}[1m])) / sum(rate(db_client_operation_duration_seconds_count{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(db_client_operation_duration_seconds_bucket{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(db_client_operation_duration_seconds_bucket{cluster=\"$cluster\", job=\"$application\", instance=~\"$pod\"}[1m])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}