apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: tempo_rules
    namespace: integration-tempo
spec:
    rules:
        - labels: {}
          name: cluster_namespace_job_route:tempo_request_duration_seconds:99quantile
          query: histogram_quantile(0.99, sum by (le, cluster, namespace, job, route) (rate(tempo_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:tempo_request_duration_seconds:50quantile
          query: histogram_quantile(0.5, sum by (le, cluster, namespace, job, route) (rate(tempo_request_duration_seconds_bucket[1m])))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:tempo_request_duration_seconds:avg
          query: sum by (cluster, namespace, job, route) (rate(tempo_request_duration_seconds_sum[1m])) / sum by (cluster, namespace, job, route) (rate(tempo_request_duration_seconds_count[1m]))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:tempo_request_duration_seconds_bucket:sum_rate
          query: sum by (le, cluster, namespace, job, route) (rate(tempo_request_duration_seconds_bucket[1m]))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:tempo_request_duration_seconds_sum:sum_rate
          query: sum by (cluster, namespace, job, route) (rate(tempo_request_duration_seconds_sum[1m]))
          type: recording
        - labels: {}
          name: cluster_namespace_job_route:tempo_request_duration_seconds_count:sum_rate
          query: sum by (cluster, namespace, job, route) (rate(tempo_request_duration_seconds_count[1m]))
          type: recording


