{
 "title": "Docker logs",
 "tags": [ "docker-integration" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({job!=\"kubelet\", namespace=\"\" ,container!=\"\"}, job)"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   {
    "name": "name",
    "label": "Container Name",
    "query": {}
   },
   { "name": "regex_search", "label": "Regex search" }
  ]
 },
 "panels": [
  { "title": "Integration Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\",tenant=~\"$tenant\",instance=~\"$instance\",container=~\"$name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $regex_search",
   "type": "stat",
   "description": "Total Count: of $regex_searchin the specified time range",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\",tenant=~\"$tenant\",instance=~\"$instance\",container=~\"$name\"}|~ \"(?i)$regex_search\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Shows if logs are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 7, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"integrations/docker\",tenant=~\"$tenant\", instance=~\"$instance\", container=~\"$name\"}[$__auto]))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 7, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"integrations/docker\",tenant=~\"$tenant\",instance=~\"$instance\", container=~\"$name\"}[$__auto]))\n"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Logs volume grouped by \"container\" label.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container) (count_over_time({job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\",tenant=~\"$tenant\",instance=~\"$instance\",container=~\"$name\"}\n|~ \"$regex_search\"\n\n[$__interval]))\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\",tenant=~\"$tenant\",instance=~\"$instance\",container=~\"$name\"} \n|~ \"(?i)$regex_search\"\n\n\n| label_format timestamp=\"{{__timestamp__}}\"\n| line_format `{{ if eq \"[[instance]]\" \".*\" }}{{alignLeft 25 .instance}}|{{ alignLeft 25 .container }}|{{else}}{{ alignLeft 25 .container}}|{{end}} {{__line__}}`\n"
    }
   ]
  }
 ]
}