apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: windows-node-alerts
    namespace: integrations-windows-node
spec:
    rules:
      - alert: WindowsCPUHighUsage
        expr: >
          100 - (avg without (mode, core) (rate(windows_cpu_time_total{job=~"integrations/windows-exporter", mode="idle"}[2m])) * 100) > 90
        for: 15m
        keep_firing_for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Node
          asserts_severity: warning
          severity: warning
        annotations:
          description: >
            CPU usage on host {{ $labels.instance }} is above 90%. The current value is {{ $value | printf "%.2f" }}%.
          summary: High CPU usage on Windows host.
      - alert: WindowsDiskAlmostOutOfSpace
        expr: >
          100 - ((windows_logical_disk_free_bytes{job=~"integrations/windows-exporter"} ) / (windows_logical_disk_size_bytes{job=~"integrations/windows-exporter"})) * 100  > 90
        for: 15m
        keep_firing_for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Node
          asserts_severity: critical
          severity: critical
        annotations:
          description: >
            Volume {{ $labels.volume }} is almost full on host {{ $labels.instance }}, more than 90% of space is used. The current volume utilization is {{ $value | printf "%.2f" }}%.
          summary: Disk is almost full on Windows host.
      - alert: WindowsDiskDriveNotHealthy
        expr: >
          windows_disk_drive_status{job=~"integrations/windows-exporter", status="OK"} != 1
        for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Node
          asserts_severity: critical
          severity: critical
        annotations:
          description: >
            Windows disk {{ $labels.name }} is not in healthy state, currently in '{{ $labels.status }}' status.
          summary: Windows physical disk is not healthy.
      - alert: WindowsMemoryHighUtilization
        expr: >
          100 - ((windows_os_physical_memory_free_bytes{job=~"integrations/windows-exporter"}

          /

          windows_cs_physical_memory_bytes{job=~"integrations/windows-exporter"}) * 100) > 90
        for: 15m
        keep_firing_for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Node
          asserts_severity: critical
          severity: critical
        annotations:
          description: >
            Memory usage on host {{ $labels.instance }} is above 90%. The current value is {{ $value | printf "%.2f" }}%.
          summary: High memory usage on Windows host.
      - alert: WindowsNTPClientDelay
        expr: >
          windows_time_ntp_round_trip_delay_seconds{job=~"integrations/windows-exporter"} > 1
        for: 5m
        keep_firing_for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Node
          asserts_severity: warning
          severity: warning
        annotations:
          description: >
            Round-trip time of NTP client on instance {{ $labels.instance }} is greater than 1 second. Delay is {{ $value }} sec.
          summary: NTP client delay.
      - alert: WindowsNTPTimeOffset
        expr: >
          windows_time_computed_time_offset_seconds{job=~"integrations/windows-exporter"} > 1
        for: 5m
        keep_firing_for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Node
          asserts_severity: warning
          severity: warning
        annotations:
          description: >
            NTP time offset for instance {{ $labels.instance }} is greater than 1 second. Offset is {{ $value }} sec.
          summary: NTP time offset is too large.
      - alert: WindowsServiceNotHealthy
        expr: >
          windows_service_status{job=~"integrations/windows-exporter", status!~"starting|stopping|ok"} > 0
        for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Node
          asserts_severity: critical
          severity: critical
        annotations:
          description: >
            Windows service {{ $labels.name }} is not in healthy state, currently in '{{ $labels.status }}'.
          summary: Windows service is not healthy.
