{
 "title": "Windows Overview",
 "tags": [ "integration-windows-node" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Asserts environment",
    "query": "label_values(asserts:mixin_workload_job, asserts_env)"
   },
   {
    "name": "site",
    "label": "Asserts site",
    "query": "label_values(asserts:mixin_workload_job{asserts_env=~\"$env\"}, asserts_site)"
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\", cluster=~\"$cluster\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The duration of time that has passed since the last reboot or system start.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_boot_time_timestamp_seconds{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\nor\ntime() - windows_system_boot_time_timestamp{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\nor\ntime() - windows_system_system_up_time{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "description": "System's hostname.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_info{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "OS version",
   "type": "stat",
   "description": "Version of Windows operating system.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_info{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "OS family",
   "type": "stat",
   "description": "OS family includes various versions and editions of the Windows operating system.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_info{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "description": "CPU count is the number of processor cores or central processing units (CPUs) in a computer,\ndetermining its processing capability and ability to handle tasks concurrently.\n",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cpu_logical_processor{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\nor\nwindows_cs_logical_processors{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "description": "Amount of random-access memory (RAM) installed.\nIt represents the system's available working memory that applications and the operating system use to perform tasks.\nA higher memory total generally leads to better system performance and the ability to run more demanding applications and processes simultaneously.\n",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\nor\nwindows_memory_physical_total_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    }
   ]
  },
  {
   "title": "Pagefile size",
   "type": "stat",
   "description": "A page file (also known as a \"paging file\") is an optional, hidden system file on a hard disk.\nPage files enable the system to remove infrequently accessed modified pages from physical memory to let the system use physical memory more efficiently for more frequently accessed pages.\n\nhttps://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/introduction-to-the-page-file\n",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_paging_limit_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\nor\nwindows_pagefile_limit_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk C: size",
   "type": "stat",
   "description": "Total storage capacity on the primary hard drive (usually the system drive) of a computer running a Windows operating system.\n",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", volume=\"C:\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg without (mode,core) (rate(windows_cpu_time_total{asserts_env=~\"$env\", asserts_site=~\"$site\", mode=\"idle\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg without (mode,core) (rate(windows_cpu_time_total{asserts_env=~\"$env\", asserts_site=~\"$site\", mode=\"idle\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - windows_memory_physical_free_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} / windows_memory_physical_total_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} * 100\nor\n100 - windows_os_physical_memory_free_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in bytes.\n",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} - windows_os_physical_memory_free_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\nor\nwindows_memory_physical_total_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} - windows_memory_physical_free_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory used"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\nor\nwindows_memory_physical_total_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Disk reads/writes",
   "type": "timeseries",
   "description": "Disk read/writes in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{asserts_env=~\"$env\", asserts_site=~\"$site\", volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ volume }} read"
    },
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{asserts_env=~\"$env\", asserts_site=~\"$site\", volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ volume }} written"
    },
    {
     "expr": "(1-clamp_max(irate(windows_logical_disk_idle_seconds_total{asserts_env=~\"$env\", asserts_site=~\"$site\", volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]),1)) * 100",
     "legendFormat": "{{ volume }} io util"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "table",
   "description": "This table provides information about total disk space, used space, available space, and usage percentages for each mounted file system on the system.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "windows_logical_disk_free_bytes{asserts_env=~\"$env\", asserts_site=~\"$site\", volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ volume }} available"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Network traffic (bits per sec) measures data transmitted and received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{ nic }} received"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{ nic }} transmitted"
    }
   ]
  },
  {
   "title": "Network errors and dropped packets",
   "type": "timeseries",
   "description": "**Network errors**:\n\nNetwork errors refer to issues that occur during the transmission of data across a network. \n\nThese errors can result from various factors, including physical issues, jitter, collisions, noise and interference.\n\nMonitoring network errors is essential for diagnosing and resolving issues, as they can indicate problems with network hardware or environmental factors affecting network quality.\n\n**Dropped packets**:\n\nDropped packets occur when data packets traveling through a network are intentionally discarded or lost due to congestion, resource limitations, or network configuration issues. \n\nCommon causes include network congestion, buffer overflows, QoS settings, and network errors, as corrupted or incomplete packets may be discarded by receiving devices.\n\nDropped packets can impact network performance and lead to issues such as degraded voice or video quality in real-time applications.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_errors_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ nic }} transmitted"
    },
    {
     "expr": "irate(windows_net_packets_received_errors_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ nic }} received"
    },
    {
     "expr": "irate(windows_net_packets_received_unknown_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ nic }} received (unknown)"
    },
    {
     "expr": "irate(windows_net_packets_outbound_discarded_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ nic }} transmitted packets dropped"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded_total{asserts_env=~\"$env\", asserts_site=~\"$site\", job=~\"integrations/windows_exporter\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ nic }} received packets dropped"
    }
   ]
  }
 ]
}