{
 "title": "Beyla debug",
 "tags": [ "beyla" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Beyla Version",
   "type": "stat",
   "description": "Deployed version of Beyla",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beyla_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DaemonSet: Running pods",
   "type": "stat",
   "description": "Number of running pods",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{daemonset=\"duplo-monitoring-beyla\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL metric exports",
   "type": "stat",
   "description": "Number of metric exports",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(beyla_otel_metric_exports_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL trace exports",
   "type": "stat",
   "description": "Number of trace exports",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(beyla_otel_trace_exports_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Processes",
   "type": "table",
   "description": "Discovered processes",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(process_name) (beyla_instrumented_processes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Amount of memory being used",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{job=\"prometheus.scrape.beyla_applications\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Amount of CPU used",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(process_command) (process_cpu_utilization_ratio{job=\"prometheus.scrape.beyla_applications\"})",
     "legendFormat": "{{process_command}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"integrations/beyla\"} | logfmt | component!=`BPFLogger`"
    }
   ]
  },
  {
   "title": "BPF Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{job=\"integrations/beyla\"} |= `ebpf`"
    }
   ]
  },
  {
   "title": "Application Errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{job=\"integrations/beyla\"} |= `ERROR`"
    }
   ]
  }
 ]
}