{
 "title": "Service Dashboard",
 "description": "Service Level Dashboard",
 "tags": [
  "apm",
  "service",
  "tempo-mg",
  "main"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{source=\"tempo\"},k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{source=\"tempo\", k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{source=\"tempo\", k8s_cluster_name=\"$cluster\", k8s_namespace_name=\"$namespace\", span_kind!=\"SPAN_KIND_CLIENT\"},service)"
    }
   },
   {
    "name": "rate_interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 🚨 Investigate RED Metrics\n\nPlease drill down to a 3-hour time window.\nThen, open the 🔗 Rate, Errors & Duration metrics panel links to investigate further."
   }
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (service)",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", status_code=\"STATUS_CODE_ERROR\"} [$rate_interval])) by (service) OR sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (service) * 0) / sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (service)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (le,service))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (le,service))",
     "legendFormat": "P95"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (service) / (sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (service))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Duration distribution",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (increase(traces_spanmetrics_latency_bucket{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (le,span_name))"
    },
    {
     "expr": "(sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\", status_code=\"STATUS_CODE_ERROR\"} [$rate_interval])) by (span_name) OR sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (span_name) * 0) / sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (span_name)"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", service=~\"$service\"} [$rate_interval])) by (span_name)"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_service_graph_request_server_seconds_bucket{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", server=~\"$service\", client!=\"user\"} [$rate_interval])) by (le, client, k8s_cluster_name, k8s_namespace_name))"
    },
    {
     "expr": "(sum(rate(traces_service_graph_request_failed_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", server=~\"$service\", client!=\"user\"} [$rate_interval])) by (client, k8s_cluster_name, k8s_namespace_name) OR sum(rate(traces_service_graph_request_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", server=~\"$service\", client!=\"user\"} [$rate_interval])) by (client, k8s_cluster_name, k8s_namespace_name) * 0) / sum(rate(traces_service_graph_request_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", server=~\"$service\",  client!=\"user\"} [$rate_interval])) by (client, k8s_cluster_name, k8s_namespace_name)"
    },
    {
     "expr": "sum(rate(traces_service_graph_request_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", server=~\"$service\", client!=\"user\"} [$rate_interval])) by (client, k8s_cluster_name, k8s_namespace_name)"
    }
   ]
  },
  {
   "title": "Outbound & databases",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_service_graph_request_server_seconds_bucket{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", client=~\"$service\"} [$rate_interval])) by (le, server, k8s_cluster_name, k8s_namespace_name))"
    },
    {
     "expr": "(sum(rate(traces_service_graph_request_failed_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", client=~\"$service\"} [$rate_interval])) by (server, k8s_cluster_name, k8s_namespace_name) OR sum(rate(traces_service_graph_request_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", client=~\"$service\"} [$rate_interval])) by (server, k8s_cluster_name, k8s_namespace_name) * 0) / sum(rate(traces_service_graph_request_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", client=~\"$service\"} [$rate_interval])) by (server, k8s_cluster_name, k8s_namespace_name)"
    },
    {
     "expr": "sum(rate(traces_service_graph_request_total{source=\"tempo\", k8s_cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", client=~\"$service\"} [$rate_interval])) by (server, k8s_cluster_name, k8s_namespace_name)"
    }
   ]
  }
 ]
}