{
 "title": "OpenTelemetry APM",
 "description": "A language-agnostic application performance management(APM) with OpenTelemetry, Grafana, and Prometheus.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total,service)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{service=\"$app\", source=\"tempo\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total{source=\"tempo\", span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\"}[$__rate_interval])) by(service)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_spanmetrics_calls_total{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^2.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 2XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^3.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 3XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^4.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 4XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^5.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 5XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^2.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 2XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^3.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 3XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^4.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 4XX"
    },
    {
     "expr": "sum(duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^5.*\", http_route=~\"$route\"}) by(http_status_code)",
     "legendFormat": "Http Status 5XX"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\"}[$__interval])) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_latency_sum{source=\"tempo\", span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\"}[$__interval])) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\"}[3m])*60)"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total{source=\"tempo\", span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", status_code=\"STATUS_CODE_ERROR\", span_name=~\"$route\"}[$__interval]))\r\n/\r\nsum(increase(traces_spanmetrics_calls_total{source=\"tempo\", span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\"}[$__interval]))\r\n"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$app\", span_kind=\"SPAN_KIND_SERVER\", span_name=~\"$route\", source=\"tempo\"}[3m])*60)  by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PR95 Latency",
   "type": "timeseries",
   "description": "PR95 latency over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\", source=\"tempo\"}[3m])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(traces_spanmetrics_latency_sum{source=\"tempo\", span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\",}) by (span_name) / sum(traces_spanmetrics_latency_count{source=\"tempo\", span_kind=\"SPAN_KIND_SERVER\", service=\"$app\", span_name=~\"$route\", }) by (span_name))",
     "legendFormat": "[{{http_status_code}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=\"$app\", span_name=~\"$route\", span_kind=\"SPAN_KIND_SERVER\", source=\"tempo\"}[3m])*60) by(service, span_name)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"$app\", span_name=~\"$route\", span_kind=\"SPAN_KIND_SERVER\", source=\"tempo\"}[3m])) by (le, service,span_name))"
    },
    {
     "expr": "sum(traces_spanmetrics_calls_total{service=\"$app\", span_name=~\"$route\", span_kind=\"SPAN_KIND_SERVER\", status_code=\"STATUS_CODE_ERROR\", source=\"tempo\"}) by(service, span_name) / sum(traces_spanmetrics_calls_total{service=\"$app\", span_name=~\"$route\", span_kind=\"SPAN_KIND_SERVER\", source=\"tempo\"}) by(service, span_name)"
    }
   ]
  }
 ]
}