apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: baseline-stddev-1h
    namespace: app-o11y
spec:
    rules:
        - labels: {}
          name: appo11y:request:rate5m:stddev_st_1h
          query: stddev_over_time(appo11y:request:rate5m:select[1h]) > appo11y:request:rate5m:prediction_st * on () group_left () appo11y:request:stddev:threshold_by_covar
          type: recording
          interval: 300
        - labels: {}
          name: appo11y:duration:p95:stddev_1h
          query: stddev_over_time(appo11y:duration:p95[1h]) unless (appo11y:request:rate5m unless appo11y:request:rate5m:select) > avg_over_time(appo11y:duration:p95[1h]) * on () group_left () appo11y:duration:stddev:threshold_by_covar
          type: recording
          interval: 300
        - labels: {}
          name: appo11y:error:ratio:stddev_1h
          query: stddev_over_time(appo11y:error:ratio[1h])
          type: recording
          interval: 300