apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: baseline-request-rate
    namespace: app-o11y
spec:
    rules:
        - labels: {}
          name: appo11y:request:rate5m
          query: sum by (k8s_cluster_name, k8s_namespace_name, service, span_name) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER"}[5m] offset 1m))
          type: recording
        - labels:
            span_name: __aggregated__
          name: appo11y:request:rate5m
          query: sum by (k8s_cluster_name, k8s_namespace_name, service) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER"}[5m] offset 1m))
          type: recording
        - labels: {}
          name: appo11y:request:rate5m:select
          query: appo11y:request:rate5m > 0 and (max_over_time(appo11y:request:rate5m[1h] offset 23h30m) > 0 or max_over_time(appo11y:request:rate5m[1h] offset 6d23h30m) > 0) unless avg_over_time(appo11y:request:rate5m[1h]) < on () group_left () appo11y:request:rate:sparse_threshold
          type: recording
        - labels: {}
          name: appo11y:request:rate5m:prediction_st
          query: avg_over_time(appo11y:request:rate5m:select[1h])
          type: recording
        - labels: {}
          name: appo11y:request:rate5m:stddev_st
          query: avg_over_time(appo11y:request:rate5m:stddev_st_1h[1d2h])
          type: recording
        - labels: {}
          name: appo11y:request:rate5m:anomaly_lower_threshold
          query: clamp_min(min without (prediction_type) (label_replace(last_over_time(appo11y:request:rate5m:prediction_st[2m]) - last_over_time(appo11y:request:rate5m:stddev_st[2m]) * on () group_left () appo11y:request:rate:threshold_by_stddev, "prediction_type", "short_term", "", "") or label_replace(last_over_time(appo11y:request:rate5m:prediction_st[2m]) - last_over_time(appo11y:request:rate5m:prediction_st[2m]) * on () group_left () appo11y:request:rate:threshold_margin, "prediction_type", "margin", "", "") or last_over_time((min without (look_back) (label_replace(avg_over_time(appo11y:request:rate5m:select[1h] offset 6d23h30m) - stddev_over_time(appo11y:request:rate5m:select[1h] offset 6d23h30m) * on () group_left () appo11y:request:rate:threshold_by_stddev, "look_back", "1w", "", "") or label_replace(avg_over_time(appo11y:request:rate5m:select[1h] offset 23h30m) - stddev_over_time(appo11y:request:rate5m:select[1h] offset 23h30m) * on () group_left () appo11y:request:rate:threshold_by_stddev, "look_back", "1d", "", "")))[10m:1m])), 0)
          type: recording
        - labels: {}
          name: appo11y:request:rate5m:anomaly_upper_threshold
          query: max without (prediction_type) (label_replace(last_over_time(appo11y:request:rate5m:prediction_st[2m]) + last_over_time(appo11y:request:rate5m:stddev_st[2m]) * on () group_left () appo11y:request:rate:threshold_by_stddev, "prediction_type", "short_term", "", "") or label_replace(last_over_time(appo11y:request:rate5m:prediction_st[2m]) + last_over_time(appo11y:request:rate5m:prediction_st[2m]) * on () group_left () appo11y:request:rate:threshold_margin, "prediction_type", "margin", "", "") or last_over_time((max without (look_back) (label_replace(avg_over_time(appo11y:request:rate5m:select[1h] offset 6d23h30m) + stddev_over_time(appo11y:request:rate5m:select[1h] offset 6d23h30m) * on () group_left () appo11y:request:rate:threshold_by_stddev, "look_back", "1w", "", "") or label_replace(avg_over_time(appo11y:request:rate5m:select[1h] offset 23h30m) + stddev_over_time(appo11y:request:rate5m:select[1h] offset 23h30m) * on () group_left () appo11y:request:rate:threshold_by_stddev, "look_back", "1d", "", "")))[10m:1m]))
          type: recording