apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
    name: baseline-error-ratio
    namespace: app-o11y
spec:
    rules:
        - labels: {}
          name: appo11y:error:ratio
          query: (sum by (k8s_cluster_name, k8s_namespace_name, service, span_name) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER",status_code="STATUS_CODE_ERROR"}[5m] offset 1m)) or sum by (k8s_cluster_name, k8s_namespace_name, service, span_name) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER"}[5m] offset 1m)) * 0) / sum by (k8s_cluster_name, k8s_namespace_name, service, span_name) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER"}[5m] offset 1m))
          type: recording
        - labels:
            span_name: __aggregated__
          name: appo11y:error:ratio
          query: (sum by (k8s_cluster_name, k8s_namespace_name, service,) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER",status_code="STATUS_CODE_ERROR"}[5m] offset 1m)) or sum by (k8s_cluster_name, k8s_namespace_name, service,) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER"}[5m] offset 1m)) * 0) / sum by (k8s_cluster_name, k8s_namespace_name, service,) (rate(traces_spanmetrics_latency_count{source="tempo", span_kind=~"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER"}[5m] offset 1m))
          type: recording
        - labels: {}
          name: appo11y:error:ratio:prediction
          query: avg_over_time(appo11y:error:ratio[1h])
          type: recording
        - labels: {}
          name: appo11y:error:ratio:stddev
          query: avg_over_time(appo11y:error:ratio:stddev_1h[1d2h])
          type: recording
        - labels: {}
          name: appo11y:error:ratio:anomaly_upper_threshold
          query: clamp_max(max without (prediction_type) (label_replace(last_over_time(appo11y:error:ratio:prediction[1m]) + last_over_time(appo11y:error:ratio:stddev[1m]) * on () group_left () appo11y:error:ratio:threshold_by_stddev, "prediction_type", "stddev", "", "") or label_replace(last_over_time(appo11y:error:ratio:prediction[1m]) + last_over_time(appo11y:error:ratio:prediction[1m]) * on () group_left () appo11y:error:ratio:threshold_margin, "prediction_type", "margin", "", "")), 1)
          type: recording