{
 "title": "SLO Overview",
 "tags": [ "slo-overview" ],
 "panels": [
  {
   "title": "Above Target (1 day)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1d",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_success_rate_5m < 1e308)[1d:5m]))\n\t\t  / sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_total_rate_5m < 1e308)[1d:5m]))\n\t\t  # combine with series that aren't producing duplo_slo_success_rate_5m and duplo_slo_total_rate_5m\n\t\t  or avg by (duplo_slo_uuid) (duplo_slo_sli_1d)\n\t\t)\n\t\t> on(duplo_slo_uuid) duplo_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Above Target (6 hour)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 6h",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_success_rate_5m < 1e308)[6h:5m]))\n\t\t  / sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_total_rate_5m < 1e308)[6h:5m]))\n\t\t  # combine with series that aren't producing duplo_slo_success_rate_5m and duplo_slo_total_rate_5m\n\t\t  or avg by (duplo_slo_uuid) (duplo_slo_sli_6h)\n\t\t)\n\t\t> on(duplo_slo_uuid) duplo_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Above Target (1 hour)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1h",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_success_rate_5m < 1e308)[1h:5m]))\n\t\t  / sum by (duplo_slo_uuid) (sum_over_time((duplo_slo_total_rate_5m < 1e308)[1h:5m]))\n\t\t  # combine with series that aren't producing duplo_slo_success_rate_5m and duplo_slo_total_rate_5m\n\t\t  or avg by (duplo_slo_uuid) (duplo_slo_sli_1h)\n\t\t)\n\t\t> on(duplo_slo_uuid) duplo_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLOs Defined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector($input_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SLOs Recording",
   "type": "stat",
   "description": "The number of SLOs that are recording values",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (duplo_slo_uuid)(duplo_slo_sli_5m)) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recorded SLI Series",
   "type": "stat",
   "description": "The total number of series created by SLO recording rules.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"duplo_slo_.*\", duplo_slo_uuid!=\"\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 110px; font-family: Arial, sans-serif;\">\r\n    <a href=\"/d/manage-slo/manage-slo\" \r\n       style=\"display: inline-block; padding: 15px 30px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px; font-size: 20px;\">\r\n        Create SLO\r\n    </a>\r\n</div>"
   }
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"font-family: Arial, sans-serif; margin: 10px;\">\r\n    <div style=\"text-align: center;\">\r\n        <span style=\"font-weight: bold;\">\r\n            $name: \r\n        </span>\r\n        <span>\r\n            $description\r\n        </span>\r\n    </div>\r\n    <div style=\"text-align: center; margin-top: 10px;\">\r\n        <a href=\"/d/$duplo_uuid/$name-$duplo_uuid\" \r\n           style=\"display: inline-block; padding: 8px 20px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px; font-size: 14px; margin: 5px;\">\r\n            View Dashboard\r\n        </a>\r\n        <a href=\"/d/manage-slo/manage-slo\" \r\n           style=\"display: inline-block; padding: 8px 20px; background-color: #28a745; color: white; text-decoration: none; border-radius: 5px; font-size: 14px; margin: 5px;\">\r\n            Edit SLO\r\n        </a>\r\n    </div>\r\n</div>"
   }
  },
  {
   "title": "SLI (last $time_window)",
   "type": "stat",
   "description": "Service level indicator's value over the last $time_window",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# omit NaN by comparing to Infinity\nsum(sum_over_time((duplo_slo_success_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n/ sum(sum_over_time((duplo_slo_total_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "The unspent error budget over the last {$objective $time_window} Window",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((duplo_slo_success_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n\t\t/ sum(sum_over_time((duplo_slo_total_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n\t\t- on() duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"}\n\t)\n\t/ on () (1 - duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(duplo_slo_sli_5m{duplo_slo_uuid=\"$duplo_uuid\"}[$__interval:])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}