{
 "title": "$name-$duplo_uuid",
 "tags": [ "slo" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-family: Arial, sans-serif; margin: 20px; text-align: center;\">\n    <h1 style=\"margin: 0; font-size: 3em; font-weight: bold; color: rgb(255, 94, 98);\">$name</h1>\n    <h2 style=\"margin: 10px 0 0; font-size: 1.5em; font-weight: normal; color: rgb(0, 164, 239);\">$description</h2>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time Window",
   "type": "stat",
   "description": "The time window over which the service level objective is being measured over",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(vector(1), \"time_period\", \"$time_window\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "stat",
   "description": "The SLO's Objective value. Always between 0 and 100%",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector($objective)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Edit SLO",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 80px; font-family: Arial, sans-serif;\">\n    <a href=\"/d/manage-slo/manage-slo?var-duplo_uuid=$duplo_uuid\" \n       style=\"display: inline-block; padding: 10px 25px; background-color: #28a745; color: white; text-decoration: none; border-radius: 2px; font-size: 20px;\">\n        Edit SLO\n    </a>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Delete SLO",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{duplo_slo_uuid=\"$duplo_uuid\", duplo_slo_severity=\"critical\"}) OR on() vector(0)",
     "legendFormat": "Critical alert"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(duplo_slo_sli_5m{duplo_slo_uuid=\"$duplo_uuid\"}[$__interval:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "((sum(rate($success_metric[$__rate_interval] offset 2m)) or 0 * sum(rate($total_metric[$__rate_interval] offset 2m))) / sum(rate($total_metric[$__rate_interval] offset 2m))) AND timestamp(sum(rate($total_metric[$__rate_interval] offset 2m))) < $curr_ts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI (last $time_window)",
   "type": "stat",
   "description": "Service level indicator's value over the last $time_window",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# omit NaN by comparing to Infinity\nsum(sum_over_time((duplo_slo_success_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n/ sum(sum_over_time((duplo_slo_total_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{duplo_slo_uuid=\"$duplo_uuid\", duplo_slo_severity=\"warning\"}) OR on() vector(0)",
     "legendFormat": "Warning alert"
    }
   ]
  },
  {
   "title": "Burn Rate Alerts",
   "type": "alertlist",
   "description": "All active alerts for this SLO",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error Budget Trend",
   "type": "timeseries",
   "description": "If error budget is decreasing over time, it means that your service is spending its error budget faster than it's earning it back.\n\nIf error budget is increasing over time, you're not spending too much of your error budget.",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((duplo_slo_success_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n\t\t/ sum(sum_over_time((duplo_slo_total_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n\t\t- on() duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"}\n\t)\n\t/ on () (1 - duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Error Budget",
   "type": "stat",
   "description": "The unspent error budget over the last {$objective $time_window} Window",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((duplo_slo_success_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n\t\t/ sum(sum_over_time((duplo_slo_total_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$time_window:5m]))\n\t\t- on() duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"}\n\t)\n\t/ on () (1 - duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Burn Rate",
   "type": "timeseries",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg without(duplo_slo_version) (1 - avg_over_time((duplo_slo_sli_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$__interval:]))\n/ on(duplo_slo_uuid) group_left() avg without(duplo_slo_version) (1 - avg_over_time((duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$__interval:]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "((1 - ((sum(rate($success_metric[$__rate_interval] offset 2m)) or 0 * sum(rate($total_metric[$__rate_interval] offset 2m))) / sum(rate($total_metric[$__rate_interval] offset 2m)))) / (1 - $objective)) AND timestamp(sum(rate($total_metric[$__rate_interval] offset 2m))) < $curr_ts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Burn Rate",
   "type": "stat",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(duplo_slo_version) (1 - avg_over_time((duplo_slo_sli_5m{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$__interval:]))\n/ on(duplo_slo_uuid) group_left() avg without(duplo_slo_version) (1 - avg_over_time((duplo_slo_objective{duplo_slo_uuid=\"$duplo_uuid\"} < 1e308)[$__interval:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Rate",
   "type": "timeseries",
   "description": "Total Rate (for SLIs that compare rate of successful events to rate of total events, this is the latter)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (duplo_slo_uuid) (duplo_slo_total_rate_5m{duplo_slo_uuid=\"$duplo_uuid\"})"
    },
    {
     "expr": "(sum(rate($total_metric[$__rate_interval] offset 2m))) AND timestamp(sum(rate($total_metric[$__rate_interval] offset 2m))) < $curr_ts"
    }
   ]
  }
 ]
}