{
 "title": "ApplicationGateway",
 "description": "Using Azure Monitor data source, this dashboard provides insights for network monitoring. This monitoring is available for the following Azure services: Front Door, Traffic Manager, Application Gateways and Load Balancers.",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "applicationgateway",
    "query": {}
   },
   {
    "name": "resapplicationgateway",
    "label": "Application Gateways",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Application Gateways - ${resapplicationgateway}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "resapplicationgateway"
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($resapplicationgateway)\r\n| project Name=name, sku.name, location, subscriptionId\r\n| join kind=inner(\r\n    resourcecontainers\r\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\r\n        | project subscriptionId, Subscription = name\r\n) on subscriptionId\r\n| project-away subscriptionId, subscriptionId1\r\n| join kind=leftouter(\r\n    alertsmanagementresources\r\n        | where tolower(properties.context.context.resourceName) == tolower($resapplicationgateway)\r\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\r\n        | project properties_context_context_resourceName, count_, subscriptionId\r\n) on $left.Name == $right.properties_context_context_resourceName\r\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\r\n"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Throughput",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Unhealthy Host Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UnhealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Healthy Host Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Requests per Healthy Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AvgRequestCountPerHealthyHost",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FailedRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$applicationgateway/$resapplicationgateway",
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}