{
 "title": "Native_Containers",
 "description": "Dashboard with details of the container metrics and host OS metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "query": { "query": "label_values(tenant)" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({tenant=~\"^$tenant$\"}, name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({tenant=~\"^$tenant$$\", name=~\"$node$\"},host_ip)"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{tenant=~\"^$tenant$\"}))"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overvie 【Node：$node，Total：$total】",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_uname_info{tenant=~\"^$tenant$\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{tenant=~\"^$tenant$\"})by(private_ip)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{tenant=~\"^$tenant$\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode='system', tenant=~\"^$tenant$\"}) by (private_ip)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{tenant=~\"^$tenant$\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", tenant=~\"^$tenant$\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tenant=~\"^$tenant$\"} / (node_memory_MemTotal_bytes{tenant=~\"^$tenant$\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{tenant=~\"^$tenant$\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{tenant=~\"^$tenant$\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{tenant=~\"^$tenant$\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{tenant=~\"^$tenant$\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{tenant=~\"^$tenant$\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{tenant=~\"^$tenant$\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\"^$node$\", id=~\"/docker/.*\",host_ip=~\"^$instance$\", tenant=~\"^$tenant$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage per Native container",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{tenant=~\"^$tenant$\",name=~\"^$node$\", container_env_role_name!=\"\"}) by (container_env_role_name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{container_env_role_name!=\"\",instance=~\"^$node$\"}-container_memory_usage_bytes{container_env_role_name!=\"\",instance=~\"^$node$\"})by (container_env_role_name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{container_env_role_name!=\"\",instance=~\"^$node$\"}) by (container_env_role_name)"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage per Native Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_env_role_name!=\"\",name=~\"^$node$\"}[5m])) by (container_env_role_name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Native Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum( container_memory_working_set_bytes{container_env_role_name!=\"\",name=~\"^$node$\"} ) by (container_env_role_name) / ignoring (container_env_role_name) group_left sum( machine_memory_bytes{}) * 100",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage per Native Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_env_role_name!=\"\",name=~\"^$node$\"}[5m])) by (container_env_role_name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}