{
 "title": "K8s Admin",
 "description": "Dashboard with details of the container metrics and host OS metrics.",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "label": "Tenant", "query": { "query": "label_values(tenant)" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({tenant=~\"^$tenant$\"}, host_friendlyname)"
    }
   },
   {
    "name": "private_ip",
    "label": "Private IP",
    "query": {
     "query": "label_values({tenant=~\"^$tenant$$\", name=~\"$node$\"},private_ip)"
    }
   },
   {
    "name": "app",
    "label": "Pod",
    "query": {
     "query": "label_values({tenant=~\"^$tenant$\", name=~\"$node$\", host_ip=~\"$private_ip$\"},app)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "total",
    "label": "Total Servers",
    "query": {
     "query": "query_result(count(node_uname_info{tenant=~\"^$tenant$\", name=~\"$node$\", host_ip=~\"$private_ip$\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Deployment Status",
   "type": "table",
   "description": "Deployments specify a number of pods of a given service that are running. This number is captured as \"total.\" \n\nPods that are running, giving good readiness and health checks are considered \"Available.\"\n\nPods that are running but failing health/readiness checks are considered \"Unavailable.\"\n\nThe final column shows the number of pods desired as defined in the kubernetes spec. This is called \"desired\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, deployment) group_left max by(namespace, deployment)(kube_deployment_status_replicas_available)",
     "legendFormat": "{{deployment}}-{{namespace}}"
    },
    {
     "expr": "kube_deployment_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, deployment) group_left max by(namespace, deployment)(kube_deployment_status_replicas_unavailable)",
     "legendFormat": "{{deployment}}-{{namespace}}"
    },
    {
     "expr": "kube_deployment_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, deployment) group_left max by(namespace, deployment)(kube_deployment_status_replicas)",
     "legendFormat": "{{deployment}}-{{namespace}}"
    },
    {
     "expr": "kube_deployment_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, deployment) group_left max by(namespace, deployment)(kube_deployment_spec_replicas)"
    }
   ]
  },
  {
   "title": "Deployment Replicas Available",
   "type": "timeseries",
   "description": "Percentage of replicas available of total replicas for the deployment depicted over the time interval. Less than 100% means that at least one pod failed or has not started.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_deployment_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * \n  on (namespace, deployment) group_left max by(namespace, deployment)(\n    kube_deployment_status_replicas_available / kube_deployment_status_replicas * 100\n  )  ",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Statefulset status",
   "type": "table",
   "description": "StatefulSets manage Pods and replication. Some services may be managed by deployments, while others are managed by StatefulSets based on the configuration of your Pods. This table displays the number of replicas that are deployed as StatefulSets for your applications.\n\nReady indicates the number of replicas that have passed Health and Readiness Checks and are ready to process workloads.* \n\nRunning indicates the number of deployed Pods, including those that have not passed Health and Readiness Checks.\n\nUnavailable indicates the number of running Pods that did not pass Health and Readiness Checks.\n\nDesired is the number of replicas specified by the StatefulSet.\n\nReady is the number of currently ready replicas - which means they are passing health and readiness checks and can therefore handle traffic. Running is a count of all pods currently deployed, regardless of if they pass health/readiness checks. Unavailable is the number of pods that are running that are not passing readiness/health checks. Desired is the number of replicas the statefulset specifies.\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_statefulset_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, statefulset) group_left max by(namespace, statefulset)(kube_statefulset_status_replicas_ready)",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_statefulset_labels{tenant=~\"^$tenant$\",label_app=~\"^$app$\"} * on (namespace, statefulset) group_left max by(namespace, statefulset)(kube_statefulset_status_replicas_current)",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_statefulset_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, statefulset) group_left max by(namespace, statefulset)(kube_statefulset_status_replicas - kube_statefulset_status_replicas_ready)",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_statefulset_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, statefulset) group_left max by(namespace, statefulset)(kube_statefulset_status_replicas_current - kube_statefulset_status_replicas_ready)",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_statefulset_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * on (namespace, statefulset) group_left max by(namespace, statefulset)(kube_statefulset_status_replicas)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Statefulset replicas ready",
   "type": "timeseries",
   "description": "Percentage of replicas ready to the total number of replicas. Less than 100% means that at least one replica is unavailable.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_statefulset_labels{tenant=~\"^$tenant$\",app=~\"^$app$\"} * \n  on (namespace, statefulset) group_left ()(\n    kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas * 100\n  ) ",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Server Resource Overview 【Node：$node，Total：$total】",
   "type": "table",
   "description": "Displays common metrics about the servers running in a given tenant. Some notes: if multiple network cards or multiple partitions exist, the value of the network card or partition with the highest utilization rate collected is displayed. \n\nCurrEstab is the number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.\n\nTCP_TW - number of sockets ending TIME_WAIT status after normal timeout. \n\n5m load measures % of a single cpu used - for example, if it is 4 it means that 4 cpu cores are fully used.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_uname_info{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{tenant=~\"^$tenant$\",name=~\"$node$\",private_ip=~\"$private_ip\"})by(private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{tenant=~\"^$tenant$\",name=~\"$node$\",private_ip=~\"$private_ip\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode='system', tenant=~\"^$tenant$\",name=~\"$node$\",private_ip=~\"$private_ip\"}) by (private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"}[$interval])) by (private_ip)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tenant=~\"^$tenant$\",name=~\"$node$\",private_ip=~\"$private_ip\"} / (node_memory_MemTotal_bytes{tenant=~\"^$tenant$\",name=~\"$node$\",private_ip=~\"$private_ip\"})))* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\", mountpoint=\"/\",name=~\"$node$\",private_ip=~\"$private_ip\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\",mountpoint=\"/\",name=~\"$node$\",private_ip=~\"$private_ip\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\",mountpoint=\"/\",name=~\"$node$\",private_ip=~\"$private_ip\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\",mountpoint=\"/\",name=~\"$node$\",private_ip=~\"$private_ip\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"^$tenant$\",mountpoint=\"/\",name=~\"$node$\",private_ip=~\"$private_ip\"})))by(private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"}[$interval])) by (private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"}[$interval])) by (private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_sockstat_TCP_tw{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"}[$interval])*8) by (private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{tenant=~\"^$tenant$\", name=~\"$node$\",private_ip=~\"$private_ip\"}[$interval])*8) by (private_ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Total number of containers connected to metrics during of the time range specified for this dashboard.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id=~\"/kubepods/.*\",host_friendlyname=~\"^$node$\",tenant=~\"^$tenant$\",app=~\"^$app$\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage/Pod",
   "type": "table",
   "description": "The CPU utilization is the percentage of a single CPU used by a pod. If it is 400% it means that it is using 4 cpus on the host.",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container_label_io_kubernetes_container_name!=\"\", container_label_io_kubernetes_container_name!=\"POD\", tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"}[1m])) by (pod, tenant)  * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage/pod",
   "type": "table",
   "description": "This table shows how much memory is being used by each pod. Actively Used Memory is working memory used, which is what the out of memory police look at when trying to kill pods. Total used memory includes files that are cached and can be evacuated. Avaialble memory is the memory limit minus the actively used memory. Memory Limit is the limit specified on the pod spec for memory utilization by a pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{ container_label_io_kubernetes_pod_name!=\"\", tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"}) by (tenant,container_label_io_kubernetes_pod_name)"
    },
    {
     "expr": "max(container_memory_usage_bytes{ container_label_io_kubernetes_pod_name!=\"\", tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"}) by (tenant,container_label_io_kubernetes_pod_name)"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_io_kubernetes_pod_name!=\"\",tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"}-container_memory_working_set_bytes{container_label_io_kubernetes_pod_name!=\"\",tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"})by (tenant,container_label_io_kubernetes_pod_name)"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_io_kubernetes_pod_name!=\"\",tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"}) by (tenant,container_label_io_kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "CPU Usage/Pod",
   "type": "timeseries",
   "description": "The CPU utilization is the percentage of a single CPU used by a pod. If it is 400% it means that it is using 4 cpus on the host.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container_label_io_kubernetes_container_name!=\"\", container_label_io_kubernetes_container_name!=\"POD\", tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"}[1m])) by (tenant, pod)  * 100",
     "legendFormat": "{{pod}} - Tenant: {{tenant}}"
    }
   ]
  },
  {
   "title": "Memory Usage/Pod",
   "type": "timeseries",
   "description": "Memory utilization per pod. This tracks the working memory utilization per pod, which does not include optional memory usage such as cached files etc, but is what Kubernetes's OOM killer tracks against the pod memory limit.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_name!=\"\",tenant=~\"^$tenant$\",host_friendlyname=~\"^$node$\",host_ip=~\"^$private_ip$\",app=~\"^$app$\"}) by (container_label_io_kubernetes_pod_name, tenant) / 1024 /1024",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}- Tenant: {{ tenant }}"
    }
   ]
  }
 ]
}