{
 "title": "Microsoft Azure Monitor Database",
 "description": "Use Azure Monitor to view relevante information of Database",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Namespaces",
    "label": "Namespaces",
    "query": {}
   },
   {
    "name": "ResourceName",
    "label": "ResourceName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Storage Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "backup_storage_used",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_used",
      "metricNamespace": "$Namespaces",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Storage Limit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_limit",
      "metricNamespace": "$Namespaces",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "SPACE %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "$Namespaces",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "$Namespaces",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "cpu_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "subscriptions": [
      "143ffc59-9394-4ec6-8f5a-c408a238be62"
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "active_connections",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Failed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "connections_failed",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "resourceUri": "/subscriptions/$Subscriptions/resourceGroups/$ResourceGroup/providers/$Namespaces/$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  }
 ]
}