{
 "title": "Node v2 Updated",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "label": "Tenant", "query": { "query": "label_values(tenant)" } },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values({tenant=~\"$tenant$\"}, name)"
    }
   },
   {
    "name": "instance",
    "label": "PrivateIP",
    "query": {
     "query": "label_values({tenant=~\"$tenant$\", name=~\"$name$\"},private_ip)"
    }
   },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{tenant=~\"$tenant$\",  name=~\"$name$\",  host_ip=~\"$instance$\", device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{tenant=~\"$tenant$\",instance=~'$instance',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values({tenant=~\"$tenant$\",host_ip=~\"$instance$\"}, nodename)"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{ tenant=~\"$tenant$\", name=~\"$name$\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview (associated JOB)，Host：$name，host_ip：$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Server Resource Overvie 【Total：$total】",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{tenant=~\"$tenant$\", name=~\"$name$\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{ tenant=~\"$tenant$\", name=~\"$name$\"})by(host_ip)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode='system', tenant=~\"$tenant$\", name=~\"$name$\"}) by (host_ip)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{ tenant=~\"$tenant$\", name=~\"$name$\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", tenant=~\"$tenant$\", name=~\"$name$\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"} / (node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{ tenant=~\"$tenant$\", name=~\"$name$\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{ tenant=~\"$tenant$\", name=~\"$name$\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{ tenant=~\"$tenant$\", name=~\"$name$\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{ tenant=~\"$tenant$\", name=~\"$name$\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{ tenant=~\"$tenant$\", name=~\"$name$\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{ tenant=~\"$tenant$\", name=~\"$name$\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "$name：Overall total 5m load & average CPU used%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{ mode='system', tenant=~\"$tenant$\", name=~\"$name$\"})",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum(node_load5{ tenant=~\"$tenant$\", name=~\"$name$\"})",
     "legendFormat": "Total 5m load"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", tenant=~\"$tenant$\", name=~\"$name$\"}[$interval])) by (instance)) * 100",
     "legendFormat": "Overall average used%"
    }
   ]
  },
  {
   "title": "$name：Overall total memory & average memory used%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"} - node_memory_MemAvailable_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"} - node_memory_MemAvailable_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"}) / sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\"}))*100",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "$name：Overall total disk & average disk used%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\"})by(device,instance))))",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  { "title": "Resource Details：【$name】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{tenant=~\"$tenant$\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} / (node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} + 1)/ (node_memory_SwapTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "【$instance】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\", host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "Internet traffic per hour $device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\", mode='system'})"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total filefd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} - node_memory_MemAvailable_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} / (node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{htenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{tenant=~\"$tenant$\",name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval]) / rate(node_disk_reads_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval]) / rate(node_disk_writes_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{tenant=~\"$tenant$\",name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "node_filefd_allocated{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "switches"
    }
   ]
  }
 ]
}