{
 "title": "ALB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "us-west-2" },
   {
    "name": "albname",
    "label": "albname",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Hosts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "*", "LoadBalancer": "$albname" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Healthy Host Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "*", "LoadBalancer": "$albname" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$albname" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "3XX Responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$albname" },
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "2XX Responses by Target Groups ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$albname" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$albname" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "4XX Errors From the Load Balancer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "{{LoadBalancer}}",
     "dimensions": { "LoadBalancer": "$albname" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "5XX Errors From the Load Balancer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "alias": "{{LoadBalancer}}",
     "dimensions": { "LoadBalancer": "$albname" },
     "label": "${PROP('Dim.LoadBalancer')}",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target Response Time From the Load Balancer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "{{LoadBalancer}}",
     "dimensions": { "LoadBalancer": "$albname" },
     "label": "${PROP('Dim.LoadBalancer')}",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Errors From the Target Groups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$albname" },
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}