{
 "title": "RDS",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "us-west-2" },
   {
    "name": "dbInstance",
    "label": "dbInstance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read / Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read / Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 27 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbInstance" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}