{
 "title": "Docker (Native) Only",
 "description": "Dashboard with details of the container metrics and host OS metrics.",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cadvisor_version_info, job)"
    }
   },
   {
    "name": "tenant",
    "query": {
     "query": "label_values(cadvisor_version_info {job=~\"$job\"}, tenant)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cadvisor_version_info{tenant=~\"$tenant\",job=~\"$job\"}, name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cadvisor_version_info{tenant=~\"$tenant\",job=~\"$job\", name=~\"$node\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id=~\"/docker/.*\",instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage per Native container",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{tenant=~\"$tenant\",name=~\"$node\", container_env_role_name!=\"\"}) by (container_env_role_name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{container_env_role_name!=\"\",instance=~\"$node\"}-container_memory_usage_bytes{container_env_role_name!=\"\",instance=~\"$node\"})by (container_env_role_name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{container_env_role_name!=\"\",instance=~\"$node\"}) by (container_env_role_name)"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage per Native Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_env_role_name!=\"\",name=~\"$node\"}[5m])) by (container_env_role_name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Native Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container_env_role_name!=\"\",name=~\"$node\"}[5m])) by (container_env_role_name) / 1024 /1024",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage per Native Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_env_role_name!=\"\",name=~\"$node\"}[5m])) by (container_env_role_name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}