{
 "title": "Kafka Cluster",
 "description": "https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "us-west-2" },
   {
    "name": "clustername",
    "label": "clustername",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Disk usage by broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$clustername" },
     "metricName": "KafkaDataLogsDiskUsed",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "stat",
   "description": "Only one controller per cluster should be active at any given time.\n",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "ActiveControllerCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "CPU (User) usage by broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$clustername" },
     "metricName": "CpuUser",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network TX packets by broker",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$clustername" },
     "metricName": "NetworkTxPackets",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network RX packets by broker",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$clustername" },
     "metricName": "NetworkRxPackets",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Global Partition Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "GlobalPartitionCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "OfflinePartitionsCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Global Topic Count",
   "type": "timeseries",
   "description": "Total number of topics across all brokers in the cluster.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$clustername" },
     "metricName": "GlobalTopicCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}