{
 "title": "Node v2 Admin",
 "description": "Duplocloud Node Dashboard allows you to access metrics about nodes or individual nodes using the dropdown menu",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "label": "Tenant", "query": { "query": "label_values(tenant)" } },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values({tenant=~\"$tenant$\"}, name)"
    }
   },
   {
    "name": "instance",
    "label": "PrivateIP",
    "query": {
     "query": "label_values({tenant=~\"$tenant$\", name=~\"$name$\"},private_ip)"
    }
   },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{tenant=~\"$tenant$\",  name=~\"$name$\",  host_ip=~\"$instance$\", device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{tenant=~\"$tenant$\",instance=~'$instance',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values({tenant=~\"$tenant$\",host_ip=~\"$instance$\"}, nodename)"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{ tenant=~\"$tenant$\", name=~\"$name$\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview (associated JOB)，Host：$name，host_ip：$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Server Resource Overview 【Total：$total】",
   "type": "table",
   "description": "Displays common metrics about the servers running in a given tenant. Some notes: if multiple network cards or multiple partitions exist, the value of the network card or partition with the highest utilization rate collected is displayed. \n\nCurrEstab is the number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.\n\nTCP_TW - number of sockets ending TIME_WAIT status after normal timeout. \n\n5m load measures % of a single cpu used - for example, if it is 4 it means that 4 cpu cores are fully used.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(host_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode='system', tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}) by (host_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}[$interval])) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"} / (node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\", private_ip=~\"$instance$\"})))* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{tenant=~\"^$tenant$\", name=\"$name$\",private_ip=~\"$instance$\"}[$interval])) by (private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{tenant=~\"^$tenant$\", name=\"$name$\",private_ip=~\"$instance$\"}[$interval])) by (private_ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_sockstat_TCP_tw{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall total 5m load & average CPU used%: $name",
   "type": "timeseries",
   "description": "CPU Metrics for the query set - given by the name and tenant fields. \n\nThe red line is the count of the total number of CPU cores for all servers that show up with a given query. For example, if your selection has 2 servers with 2 cores of CPUs each, this value should be 4.\n\nThe yellow line is the sum of the 5 minute load averages for all individual nodes in the queryset. For example, if there are 2 servers with 2 cores of cpu each and each core is reporting 0.2 load average, this should be 0.8. The upper limit of this value should be the red line. If you are worried about cpu saturation, you should be worried if the load average gets close to the red line.\n\nThe blue line is a measure of average cpu usage across all nodes. It is an average of the average of all cores across the queryset. In the previous example, where each core is reporting 0.2, this percent should be 20%. If it gets higher than like 70/80% you should be worried.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{ mode='system', tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum(node_load5{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})",
     "legendFormat": "Total 5m load"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}[$interval])) by (instance)) * 100",
     "legendFormat": "Overall average used%"
    }
   ]
  },
  {
   "title": "Overall total memory & average memory used%: $name",
   "type": "timeseries",
   "description": "Disk utilization metrics for a given queryset across tenant and name fields.\n\nThe red line is the total amount of RAM on all servers in the queryset. For example, if you have 2 servers with 8 gb RAM, the red line should be 16gb. This is measured on the left y-axis.\n\nThe yellow line is total memory in use across all servers that match the queryset. It is represented on the left y-axis. If you are interested in visually seeing memory saturation, as this line gets closer to the red line, you should be worried.\n\nThe blue dots represent usage as a percent of total memory. This is useful for understanding memory saturation - e.g. if it is close to 100% it means that your memory usage is high. It's value is represented on the right y-axis.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"} - node_memory_MemAvailable_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"} - node_memory_MemAvailable_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}) / sum(node_memory_MemTotal_bytes{ tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}))*100",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "Overall total disk & average disk used%: $name",
   "type": "timeseries",
   "description": "Disk file system metrics for all servers that match the query as defined by tenant and name.\n\nThe red line is a sum total of all storage across all nodes in the queryset. For example, if there are 5 servers with 100,80,20,100,100 gb of disk storage each, the value should be 400 gb. The left y-axis relates to this metric.\n\nThe yellow line is a measure of the utilization of that storage space. If those 5 servers included in the query use 10 GB each, the yellow line should be at 50  GB. Furthermore, a visual representation of saturation is when the yellow line approaches the red line. The left y-axis relates to this metric.\n\nThe blue dots is a percentage of memory used across the entire query. It adds up all the used space and divides it by all the total memory to come up with a percentage. The right y-axis relates to this metric.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance)) - sum(avg(node_filesystem_avail_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{fstype=~\"xfs|ext.*\", tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"})by(device,instance))))",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  { "title": "Resource Details：【$name】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "This is the average time servers in this tenant have been running.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{tenant=~\"$tenant$\",name=~\"$name$\",private_ip=~\"$instance$\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "This charts utilization metrics for CPU, RAM, and SWAP for the entire query set across tenant, name and private ip. \n\nNotes:\nThe Used RAM Memory takes into account the amount of data stored in caches as used RAM. Contact Duplo team if you want the other metric.\n\n\n",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemFree_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} / (node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} + 1)/ (node_memory_SwapTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "【$instance】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table",
   "description": "the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\", host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "description": "I/O wait is the percentage of time that the CPU (or CPUs) were idle during which the system had pending I/O requests. Presence of I/O wait tells us that the system is idle when it could be processing outstanding requests. \n\nThis is the average time spent by all cpu cores in the query defined by tenant, name and hostip in the iowait state. ",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "Internet traffic per hour $device",
   "type": "timeseries",
   "description": "Internet traffic per node per hour. \n\nThe positive metrics are node network traffic received while the negative metrics are node network traffic transmitted per hour.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[60m])) by (private_hostname)",
     "legendFormat": "{{private_hostname}}_receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[60m])) by (private_hostname)",
     "legendFormat": "{{private_hostname}}_transmit"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total count of CPU Cores for all servers in the query as specified by tenant, name, private ip.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\", mode='system'})"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "description": "inodes are data structures used by the linux filesystem to describe files and folders. If ever you get an error that says \"run out of disk space\" you should check this. Once inodes are 100% used on a server, you can have issues like data loss, application crashes, OS restarts, processes not restarting and periodic tasks not firing.\n\nThis metric is the total number of free inodes across the query defined by tenant, name and instance.",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Sum of all RAM across all servers in this query, as defined by tenant, name and private ip.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total filefd",
   "type": "stat",
   "description": "Maximum number of file handles that the linux kernel will allocate.\n\nThis number is averaged over all nodes in a tenant and of a given name. To get something meaningful for this metric, it is recommended that users select a name of a single server in the drop down above.",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "description": "This chart breaks down the CPU utilization percent by different use cases - e.g. system, user, iowait and Total. Each metric is an average of all the cores of all the nodes in the query.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"system\"}[$interval])) by (host_ip) *100",
     "legendFormat": "System:  {{ name }}"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"user\"}[$interval])) by (host_ip) *100",
     "legendFormat": "User: {{host_ip}}"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"iowait\"}[$interval])) by (host_ip) *100",
     "legendFormat": "Iowait: {{ host_ip }}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",mode=\"idle\"}[$interval])) by (host_ip))*100",
     "legendFormat": "Total: {{ host_ip }}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "This chart displays memory metrics for each node in the tenant, name and private ip query.\n\nTotal memory is the total amount of memory on a node.\n\nAvailable memory is an approximation for the amount of memory available for users to do stuff with on the node.  A full explanation is available here: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773\n\nUsed memory is the total memory that is not available to users (e.g. total minus available as defined above)\n\nUsed% is a percent utilization rate of all Used memory (as defined above) divided by total memory. \n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "Total: {{name}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} - node_memory_MemAvailable_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "Used: {{name}}"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "Avaliable: {{name}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"} / (node_memory_MemTotal_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"})))* 100",
     "legendFormat": "Used% {{name}}"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "timeseries",
   "description": "Total Network usage bandwidth for all servers in the query.\n\nThese are summed across all devices on the instance. \n\nPositive values are received traffic and negative values are transmitted traffic.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[$interval])*8) by (name)",
     "legendFormat": "{{name}}_receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",device=~\"$device\"}[$interval])*8) by (name)",
     "legendFormat": "{{name}}_transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "Per server system load metrics as well as the count of CPUs. \n\n\n\nDepicted on the chart are the 1 minute average CPU load, 5 minute average CPU load, 15 minute average CPU load and the total number of cores. The Node Load statistics are a sum of the total load on each core on the server. So, if two cores are running at 60% utilization, it would be 1.2. The difference between the 1,5,15 minute loads is how long they average over. Users can visually see saturation when any of the load averages for a server approaches its number of cores.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "1m load: {{name}}"
    },
    {
     "expr": "node_load5{tenant=~\"$tenant$\",name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "5m load: {{name}}"
    },
    {
     "expr": "node_load15{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "15m load: {{name}}"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\", mode='system'}) by (cpu,name)) by (name)",
     "legendFormat": "CPU cores: {{name}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes for each drive on each host in the query.  ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}} {{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name }} {{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "timeseries",
   "description": "% of Disk space used by mountpoint and server in the query.\n\nIn some cases, the same drive device is mounted on multiple places on the linux file system of the host. Metrics are shown for each of those.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{name}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second per disk partition.\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}}: {{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}}: {{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O per interval per device for each server in the query.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}}: {{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "timeseries",
   "description": "Time spent on each read/write operation for each disk on each host over time.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval]) / rate(node_disk_reads_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}}: {{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval]) / rate(node_disk_writes_completed_total{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}}: {{device}}_Write time"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "Displays metrics found in netstat -s and sockstat commands on linux\n\nSockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "{{name}}: CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "{{name}}: TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "{{name}}: Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "{{name}}: UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{tenant=~\"$tenant$\",name=~\"$name$\",host_ip=~\"$instance$\"}",
     "legendFormat": "{{name}}: TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}} Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}}: Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{tenant=~\"$tenant$\", name=~\"$name$\",host_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}}: Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "timeseries",
   "description": "Open file descriptors: These are a kernel level metric that show how many files are open. This can become a worry if the count is increasing constantly and not going down since there is a limit on the number of open file descriptors available in a linux filesystem.\n\nContext Switches are the process of storing the current state of the CPU in the process control block for the task it's working on so this saved state can be reloaded each time the task is resumed. A high context switch rate can have an impact on server performance. ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "node_filefd_allocated{tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}",
     "legendFormat": "{{name}}: used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{tenant=~\"$tenant$\", name=~\"$name$\",private_ip=~\"$instance$\"}[$interval])",
     "legendFormat": "{{name}} switches"
    }
   ]
  }
 ]
}