{
 "title": "ELB",
 "tags": [ "Duplo Managed" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "us-west-2" },
   {
    "name": "elbname",
    "label": "elbname",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "LoadBalancerName": "$elbname" },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "LoadBalancerName": "$elbname" },
     "metricName": "EstimatedALBActiveConnectionCount",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "4XX Errors From the Load Balancer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": { "LoadBalancerName": "$elbname" },
     "metricName": "HTTPCode_Backend_4XX",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Successful Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dimensions": { "LoadBalancerName": "$elbname" },
     "metricName": "HTTPCode_Backend_2XX",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Errors From the Target Groups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dimensions": { "LoadBalancerName": "$elbname" },
     "metricName": "BackendConnectionErrors",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Healthy Hosts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "us-west-2b", "LoadBalancerName": "$elbname" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "us-west-2b", "LoadBalancerName": "$elbname" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "3XX Responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancerName": "$elbname" },
     "metricName": "HTTPCode_Backend_3XX",
     "namespace": "AWS/ELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}