{
 "title": "ElastiCache",
 "description": "Visualize AWS ElastiCache Redis metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "us-west-2" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Evictions",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Reclaimed",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesUsedForCache / ReplicationBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicationBytes",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SaveInProgress / CurrItems",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SaveInProgress",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CurrItems",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cluster CPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster", "CacheNodeId": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HyperLogLogBasedCmds / ReplicationLag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HyperLogLogBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicationLag",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cluster DatabaseMemoryUsagePercentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster", "CacheNodeId": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cluster FreeableMemory / SwapUsage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster", "CacheNodeId": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SwapUsage",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster", "CacheNodeId": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cluster NetworkBytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster", "CacheNodeId": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster", "CacheNodeId": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cmds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "GetTypeCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HashBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HashBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ListBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SetBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SetTypeCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SortedSetBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cluster" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "StringBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}