apiVersion: grizzly.grafana.com/v1alpha1
kind: Datasource
metadata:
  name: duplo-alertmanager
spec:
  name: duplo-alertmanager
  uid: duplo-alertmanager
  type: alertmanager
  editable: true
  access: proxy
  url: http://duplo-metrics-alertmanager:8080
  user: ''
  database: ''
  basicAuth: false
  isDefault: false
  jsonData:
    handleGrafanaManagedAlerts: false
    implementation: mimir