apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
    name: Integration-Kubernetes.pod-alerts
spec:
    folderUid: duplo-common
    interval: 60
    rules:
        - annotations:
            description: 'Pod `{{ $labels.pod }}` in namespace `{{ $labels.namespace }}` (cluster: `{{ $labels.cluster }}`) has restarted within the last 5 minutes.'
            summary: 'Pod restart detected: {{ $labels.namespace }}/{{ $labels.pod }}'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: duplo-metrics
              model:
                datasource:
                    type: prometheus
                    uid: duplo-metrics
                editorMode: code
                exemplar: false
                expr: sum by (cluster, namespace, pod) (increase(kube_pod_container_status_restarts_total[5m]))
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          execErrState: Error
          folderUID: duplo-common
          for: 0s
          labels:
            severity: warning
          noDataState: OK
          orgID: 1
          ruleGroup: pod-alerts
          title: PodRestartAlert
          uid: Podrestartalert
        - annotations:
            description: The Mimir Alertmanager is responding with up=0. Check pod health, service endpoints, or network access.
            summary: Mimir Alertmanager is unreachable in {{ $labels.cluster }}/{{ $labels.namespace }}
          condition: C
          data:
            - datasourceUid: duplo-metrics
              model:
                datasource:
                    type: prometheus
                    uid: duplo-metrics
                editorMode: code
                expr: min by (cluster, namespace) (up{service="duplo-metrics-alertmanager"})
                hide: false
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
              refId: C
              relativeTimeRange: {}
          execErrState: Error
          folderUID: duplo-common
          for: 0s
          labels:
            owner: duplo
            severity: critical
          noDataState: Alerting
          orgID: 1
          ruleGroup: pod-alerts
          title: MimirAlertmanagerDown
          uid: Mimiralertmanagerdown
        - annotations:
            description: A Alertmanager Webhook Failed log was detected on pod {{ $labels.pod }} in namespace {{ $labels.namespace }} within cluster {{ $labels.cluster }}.
            summary: 'Alertmanager Webhook Failed event detected on pod {{ $labels.pod }} (namespace: {{ $labels.namespace }}, cluster: {{ $labels.cluster }})'
          condition: C
          data:
            - datasourceUid: duplo-logging
              model:
                datasource:
                    type: loki
                    uid: duplo-logging
                editorMode: code
                expr: |-
                    sum by (cluster, namespace, pod) (
                      count_over_time({service_name="duplo-automation"} |= "alertmanagerWebhookFailed" [1m]))
                intervalMs: 60000
                maxDataPoints: 43200
                queryType: instant
                refId: A
              queryType: instant
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 60000
                maxDataPoints: 43200
                refId: C
                type: threshold
              refId: C
              relativeTimeRange: {}
          execErrState: Error
          folderUID: duplo-common
          for: 0s
          labels:
            owner: duplo
            severity: critical
          noDataState: OK
          orgID: 1
          ruleGroup: pod-alerts
          title: AlertmanagerWebhookFailed
          uid: AlertmanagerWebhookFailed
    title: pod-alerts