{
 "title": "Duplo Microsoft IIS applications",
 "tags": [
  "duplo-microsoft-iis-integration"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(windows_iis_requests_total{},cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace/Tenant",
    "query": "label_values(windows_iis_requests_total{cluster=~\"$cluster\"},namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_iis_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\"},job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_iis_requests_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\"},instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(windows_iis_current_application_pool_state{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The HTTP request rate for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(app, job, instance) (rate(windows_iis_worker_requests_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "description": "Requests that have resulted in errors for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(app, instance, job, status_code) (rate(windows_iis_worker_request_errors_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{app}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Websocket connection attempts",
   "type": "timeseries",
   "description": "The number of attempted websocket connections for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(app, instance, job) (increase(windows_iis_worker_websocket_connection_attempts_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]))",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Websocket connection success rate",
   "type": "timeseries",
   "description": "The success rate of websocket connection attempts for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(app, job, instance) (increase(windows_iis_worker_websocket_connection_accepted_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]) / clamp_min(increase(windows_iis_worker_websocket_connection_attempts_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]),1)) * 100",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Current worker threads",
   "type": "timeseries",
   "description": "The current number of worker threads processing requests for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(app, instance, job, state) (windows_iis_worker_threads{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"})",
     "legendFormat": "{{instance}} - {{app}} - {{state}}"
    }
   ]
  },
  {
   "title": "Thread pool utilization",
   "type": "timeseries",
   "description": "The current application thread pool utilization for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job, instance, app) (windows_iis_worker_threads{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"})/ clamp_min(sum by (job, instance, app) (windows_iis_worker_max_threads{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}),1) * 100",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  { "title": "Worker processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Current worker processes",
   "type": "timeseries",
   "description": "The current number of worker processes processing requests for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(app, job, instance) (windows_iis_current_worker_processes{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"})",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Worker process failures",
   "type": "timeseries",
   "description": "The number of worker process failures for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(windows_iis_total_worker_process_failures{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:])",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Worker process startup failures",
   "type": "timeseries",
   "description": "The number of worker process startup failures for an IIS application.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(windows_iis_total_worker_process_startup_failures{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:])",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Worker process shutdown failures",
   "type": "timeseries",
   "description": "The number of worker process shutdown failures for an IIS application.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "increase(windows_iis_total_worker_process_shutdown_failures{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:])",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Worker process ping failures",
   "type": "timeseries",
   "description": "The number of worker process ping failures for an IIS application.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "increase(windows_iis_total_worker_process_ping_failures{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:])",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "File cache hit ratio",
   "type": "timeseries",
   "description": "The current file cache hit ratio for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(job, instance, app) (increase(windows_iis_worker_file_cache_hits_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]) / clamp_min(increase(windows_iis_worker_file_cache_queries_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]),1)) * 100",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "URI cache hit ratio",
   "type": "timeseries",
   "description": "The current URI cache hit ratio for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance, job, app) (increase(windows_iis_worker_uri_cache_hits_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]) / clamp_min(increase(windows_iis_worker_uri_cache_queries_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]),1)) * 100",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Metadata cache hit ratio",
   "type": "timeseries",
   "description": "The current metadata cache hit ratio for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(job, instance, app)(increase(windows_iis_worker_metadata_cache_hits_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]) / clamp_min(increase(windows_iis_worker_metadata_cache_queries_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]),1)) * 100",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Output cache hit ratio",
   "type": "timeseries",
   "description": "The current output cache hit ratio for an IIS application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(job, instance, app) (increase(windows_iis_worker_output_cache_hits_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]) / clamp_min(increase(windows_iis_worker_output_queries_total{job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\", app=~\"$application\"}[$__interval:]),1))",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  }
 ]
}