{
 "title": "APM for OpenTelemetry Operations",
 "description": "Lightweight APM dashboard for monitoring OpenTelemetry-based services.  \n\nInstrument your applications using OpenTelemetry SDKs and send traces, metrics, and logs to Tempo for traces, a Prometheus-compatible database like Mimir for metrics, and Loki for logs. This dashboard provides a centralized view of your application's health and performance.  \n\nFor a fully managed observability stack, consider using Grafana Cloud.  \n\nLearn more about this dashboard on https://github.com/cyrille-leclerc/opentelemetry-service-dashboard.",
 "tags": [
  "apm-v4",
  "otel",
  "service",
  "operations"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics", "query": "prometheus" },
   { "name": "tempo_datasource", "label": "Traces", "query": "tempo" },
   { "name": "loki_datasource", "label": "Logs", "query": "loki" },
   {
    "name": "deployment_environment_name",
    "label": "Environment",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,deployment_environment_name)"
    }
   },
   {
    "name": "service_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{deployment_environment_name=~\"$deployment_environment_name\"},service_namespace)"
    }
   },
   {
    "name": "service_name",
    "label": "Name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_namespace=~\"$service_namespace\", deployment_environment_name=~\"$deployment_environment_name\"},service_name)"
    }
   },
   {
    "name": "http_request_method",
    "label": "Method",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=~\"$service_name\", service_namespace=~\"$service_namespace\", deployment_environment_name=~\"$deployment_environment_name\"},http_request_method)"
    }
   },
   {
    "name": "http_route",
    "label": "Route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=~\"$service_name\", service_namespace=~\"$service_namespace\", deployment_environment_name=~\"$deployment_environment_name\", http_request_method=~\"$http_request_method\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server HTTP RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "appo11y:duration:p99{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", service_name=\"$service_name\", http_request_method=~\"$http_request_method\", http_route=~\"$http_route\", http_route!=\"__aggregated__\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "appo11y:duration:p95{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", service_name=\"$service_name\", http_request_method=~\"$http_request_method\", http_route=~\"$http_route\", http_route!=\"__aggregated__\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "appo11y:duration:avg{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", service_name=\"$service_name\", http_request_method=~\"$http_request_method\", http_route=~\"$http_route\", http_route!=\"__aggregated__\"}",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric. \n\nErrors are identified by   `http.response.status_code=~\"5..\"`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "appo11y:error:ratio{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", service_name=\"$service_name\", http_request_method=~\"$http_request_method\", http_route=~\"$http_route\", http_route!=\"__aggregated__\"} * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "appo11y:request:rate5m{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", service_name=\"$service_name\", http_request_method=~\"$http_request_method\", http_route=~\"$http_route\", http_route!=\"__aggregated__\"}",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Duration distribution",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "appo11y:duration:distribution{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", service_name=\"$service_name\", http_request_method=~\"$http_request_method\", http_route=~\"$http_route\", http_route!=\"__aggregated__\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}